### ISSUE TITLE
DFTK broken on GPUs

### ISSUE THREAD

**Issue by abussy** [JuliaMolSim/DFTK.jl#1026]
It appears that PR #996 introduced an issue with DFTK on GPUs. From this PR on, simple GPU calculations fail with `KernelError: passing and using non-bitstype argument`. I am not sure where the problem lies exactly, but I will look into it.

**Comment by mfherbst** [comment]
This sometypes happens when Gpu kernels can't infer the type and need dynamic dispatch. A function barrier usually helps. Happy to discuss more in person tomorrow.
