### ISSUE TITLE
Only run a subset of tests

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaMolSim/DFTK.jl#11]
It'd be nice to have something to just run a subset of tests
https://github.com/JuliaLang/Pkg.jl/pull/1226 was recently merged, so we could have a `@tset` macro that expands to a check on ARGS and only runs the test if specified. Or just wait for someone to come up with a package that does it...

**Comment by mfherbst** [comment]
I agree, but so far it works ok with explicitly running individual files. If matters get worse and nobody took the note of JuliaLang/julia#32715 into a package, I guess we can try ourselves. Up to this point I think it's ok as is.

**Comment by mfherbst** [comment]
That is now implemented.
