### ISSUE TITLE
Potential energy preconditioning

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaMolSim/DFTK.jl#117]
In some gross-pitaevskii problems, the potential energy rather than the kinetic energy "dominates", and it is good to precondition with the potential energy. This is an interesting one because the preconditioning has to be done in real space, so good to keep that in mind for API design.

**Comment by mfherbst** [comment]
Ah ... does that imply you would also solve the whole problem in real space or just do FFTs during the preconditioning?

**Comment by antoine-levitt** [comment]
That's the point, to avoid extra FFTs during preconditionning. It can still be seen as solving the problem in reciprocal space, you just have to cache some stuff.

**Comment by antoine-levitt** [comment]
It's also possible to do things in real space, but I think we should keep the structure of doing eg the optimization "in reciprocal space" to ensure that we stay variational

**Comment by mfherbst** [comment]
Ok, I see. Than my proposed idea to use some caching "state" object could be an appealing strategy, let's see ...

**Comment by antoine-levitt** [comment]
Yes, lazy conversions with cache is very appealing. But handling mutation and storage of arrays of vectors is possibly tricky

**Comment by antoine-levitt** [comment]
Closing, we're not going to support this directly. It's easily doable now with an extra FFT; doing it natively would require some hacks
