### ISSUE TITLE
Struct for atoms

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaMolSim/DFTK.jl#118]
And simplify things like https://github.com/JuliaMolSim/DFTK.jl/blob/553db8bcc879a86a2a01d5f64caa1cff11f1aa48/src/forces.jl#L72

**Comment by mfherbst** [comment]
- Specify cartesian coordinates
- Read some standard input file formats (by relying on ASE / pymatgen)

**Comment by mfherbst** [comment]
This is essentially solved by the AtomsBase interface now.
