### ISSUE TITLE
Optimise fallback kpoint symmetry search

### ISSUE THREAD

**Issue by mfherbst** [JuliaMolSim/DFTK.jl#128]
Implement what is mentioned in https://github.com/JuliaMolSim/DFTK.jl/blob/master/src/bzmesh.jl#L133.

**Comment by antoine-levitt** [comment]
This is very weird though. Would it be possible to open an issue at spglib to complain?

**Comment by mfherbst** [comment]
I think one should. I'm not too sure about a good testcase yet. We are kind of using spglib pretty remotely (julia interface to python interface to cpp code) and reducing our problem down to a simple case reproducing the issue on the lowest level could be a bit involved (and so I have not done it yet).
