### ISSUE TITLE
Consistent names

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaMolSim/DFTK.jl#129]
**Psi** is the worst offender, because there is three things there: a psi (array of size Nb), a block of psis (array Nb x N), and a block of block of psis (array Nk of arrays Nb x N). We sometimes use `Psi`, `psi`, or various unicode names

For densities there is the RFA and the real and fourier parts. We sometimes use unicode, sometimes not

- **PWBasis** is sometimes called `pw`, sometimes `basis`
- **Kpoints** are sometimes `kpoint`, sometimes `kpt`, singular or plural
- **Occupations** are sometimes `occ`, sometimes `occupation`, singular or plural

Probably others...

**Comment by mfherbst** [comment]
Let's collect a few:

- **Temperature**: `T` versus `temperature` (T is bad because also floating-point type)

**Comment by antoine-levitt** [comment]
Another: orben

**Comment by antoine-levitt** [comment]
Also eps_F. The question there is: how much unicode do we want? I kind of like the rule of not having any unicode in externally available functions, just in function bodies, but maybe that's unnecessarily restrictive?

**Comment by antoine-levitt** [comment]
Also merge eval_psp_energy_correction and energy_psp_correction (thanks to multiple dispatch)

**Comment by mfherbst** [comment]
Also things like PreconditionerKinetic versus KineticPreconditioner and so on.

**Comment by antoine-levitt** [comment]
PWBasis is basis
Kpoints is kpoints
temperature is temperature
orben -> eigenvalues
eps_F -> εF
ψ[ik][iG,iband]
ψ[ik] ψk
ψ[ik][:,i] ψnk
No upper case at all

function bodies do their own things if they want
