### ISSUE TITLE
Precompilation times

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaMolSim/DFTK.jl#132]
They are bearable but still annoying when developing. Empirically (meaning when I ctrl-C precompilation) it seems quite a bit of time is spent in FourierTransforms.jl; can we maybe load it conditionally, or even better upstream our changes?

**Comment by mfherbst** [comment]
Well our "changes" are essentially dirty workarounds to avoid the cases where the code breaks. Upstream (i.e. Keno) made it pretty clear, that the package is basically unmaintained as of now.

But conditionally loading this part of the code makes a lot of sense actually. I'll try to come up with something with `Requires`. We depend on it anyway ...

**Comment by antoine-levitt** [comment]
An option would be to fork it so it gets precompiled separately. But requires seems like a good option too.
