### ISSUE TITLE
Implement Cohen Bergstresser model

### ISSUE THREAD

**Issue by mfherbst** [JuliaMolSim/DFTK.jl#136]
A nice test case would be to implement the [Cohen Bergstresser](https://doi.org/10.1103/PhysRev.141.789) model.

**Comment by antoine-levitt** [comment]
Can be done completely externally with the LocalPotentialFromFourier in the terms branch. A better option is to make Element abstract and have subclasses for Hgh, bare coulomb and Cohen bergstresser atoms (and other pseudo potential in the future)

**Comment by mfherbst** [comment]
... and PAW for that sake. I like that idea to subclass AbstractElement (or something like that).
