### ISSUE TITLE
spglib returned non-unitary rotation matrix

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaMolSim/DFTK.jl#138]
With silicon_lda_arbitrary_floattype in Float32. Happened on termspocalypse branch but should also appear on master.

**Comment by mfherbst** [comment]
Which version of spglib are you on ... also it could well be that it has nothing to do with the branch.

**Comment by antoine-levitt** [comment]
```
    spglib = pyimport("spglib")
    version = VersionNumber(spglib.__version__)
```
gets me v"1.12.2". My guess is that it's more a tolerance problem with float32?

**Comment by mfherbst** [comment]
That is very possible as well.

**Comment by mfherbst** [comment]
Indeed just a precision issue.
