### ISSUE TITLE
Debug spglib symmetry handling

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaMolSim/DFTK.jl#203]
And see if we can remove the warning for recent versions

**Comment by antoine-levitt** [comment]
Repro

```
using DFTK
using Plots

# Calculation parameters
kgrid = [3, 3, 3]       # k-Point grid
supercell = [1, 1, 1]   # Lattice supercell
Ecut = 15               # kinetic energy cutoff in Hartree
n_bands = 8             # number of bands to plot in the bandstructure

# Setup silicon lattice
a = 10.263141334305942  # Silicon lattice constant in Bohr
lattice = a / 2 .* [[0 1 1.]; [1 0 1.]; [1 1 0.]]
lattice = a * randn(3, 3)
Si = ElementPsp(:Si, psp=load_psp("hgh/lda/Si-q4"))
atoms = [Si => [rand(3), rand(3), rand(3)]]

model = model_LDA(lattice, atoms)
basis = PlaneWaveBasis(model, Ecut; kgrid=kgrid)
```
One possible thing is that we're missing time-reversal symmetry? Should investigate.

**Comment by antoine-levitt** [comment]
Yup, pretty sure that's what going on. The unmapped kpoints all can be mapped with the symmetry k -> -k, which we just happen to not implement. This symmetry is special, because there's a conjugation of the wavefunctions, which however should not matter for most operations. Also this symmetry is never broken unless there's a magnetic field, so it should be "safe" for eg forces etc.

**Comment by antoine-levitt** [comment]
And the reason why it's pretty rare is that 1) apparently it only applies to odd grids (not sure why, should investigate) 2) it doesn't happen for crystals with inversion symmetry

**Comment by antoine-levitt** [comment]
To be clear: this is only about the `[ Info: 62 reducible kpoints could not be generated from the irreducible kpoints returned by spglib. 62 of these are added as extra irreducible kpoints.` message. It's separate from the bug related to recent versions of spglib.

**Comment by antoine-levitt** [comment]
As a workaround if we can't be bothered to implement time-reversal symmetry we can just set the `is_time_reversal` argument to `false`

**Comment by mfherbst** [comment]
Cool! Thanks for investigating this. Yes time-reversal is something I never checked or took into consideration. It makes a lot of sense from the experience I've had during the calculations. I think for now setting `is_time_reversal` to `false` sounds like a good way to go to me.

**Comment by antoine-levitt** [comment]
Alright. Do you think that fixes all the issues with spglib or is there any other?

**Comment by mfherbst** [comment]
Might be. The strange cases I encountered had to do with supercells, which might well break time-reversal versus inversion symmetry.

**Comment by antoine-levitt** [comment]
OK even with TRS it still doesn't work. Minimal repro

```
positions = [[0, 0, 0], [0, 1/2, 1/2], [1/8, 0, 1/2], [1/8, 1/2, 0]]
atoms = [1 => positions]
bzmesh_ir_wedge([1, 2, 3], Matrix(Diagonal([1., 1., 1.])), atoms)
```

**Comment by antoine-levitt** [comment]
`positions = [[0., 0., 0.], [0, 1/2, 1/2], ]` even

**Comment by antoine-levitt** [comment]
OK so it's
```
positions = [[0, 0, 0], [0, 1/2, 1/2], [1/8, 0, 1/2], [1/8, 1/2, 0]]
atoms = [1 => positions]
bzmesh_ir_wedge([1, 2, 3], Matrix(Diagonal([1., 1., 1.])), atoms)
```
against
```
import numpy as np
import spglib

lattice = np.array([[1.0, 0.0, 0.0],
                    [0.0, 1.0, 0.0],
                    [0.0, 0.0, 1.0]])
positions = [[0., 0., 0.],
             [0., 0.5, 0.5]]
numbers= [1,] * 2
cell = (lattice, positions, numbers)
print(spglib.get_spacegroup(cell, symprec=1e-5))
mesh = [1,2,3]

#
# Gamma centre mesh
#
mapping, grid = spglib.get_ir_reciprocal_mesh(mesh, cell, is_shift=[0, 0, 0],is_time_reversal=False)

# All k-points and mapping to ir-grid points
for i, (ir_gp_id, gp) in enumerate(zip(mapping, grid)):
    print("%3d ->%3d %s" % (i, ir_gp_id, gp.astype(float) / mesh))

# Irreducible k-points
print("Number of ir-kpoints: %d" % len(np.unique(mapping)))
print(grid[np.unique(mapping)] / np.array(mesh, dtype=float))
```

The python code finds the mapping correctly, the julia doesn't

**Comment by mfherbst** [comment]
I have now removed the warning in #222 as we know what's going on. Since this issue is kind of dealt with, I would close it, even though it is not strictly speaking resolved.

**Comment by antoine-levitt** [comment]
Agreed
