### ISSUE TITLE
Non-zero forces in the silicon example

### ISSUE THREAD

**Issue by gkemlin** [JuliaMolSim/DFTK.jl#208]
When running the example file silicon.jl with `kgrid = [4,4,4]`, we get non-zero forces when computing `forces(scfres)` (the output array is `[[-0.36944959523696796, -0.23075365997138772, -2.029230333878863e-12], [0.36944959523669624, 0.23075365997089106, 1.6977489637483588e-12]]`), which does not happen with `kgrid = [1,1,1]`. 

Using `enable_bzmesh_symmetry=false` in the PlaneWaveBasis constructor enables us to avoid this issue.

**Comment by antoine-levitt** [comment]
It's most likely the nonlocal part. We need to add a loop over the symmetry operations, see the latex in the docs and comments in bzmesh.jl.

**Comment by antoine-levitt** [comment]
And it's not caught in the tests because we explicitly move away from equilibrium positions to avoid zero forces

**Comment by antoine-levitt** [comment]
let's just declare symmetries don't exist

**Comment by mfherbst** [comment]
Resolved now in #209.
