### ISSUE TITLE
uk/us spelling consistency check

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaMolSim/DFTK.jl#211]

**Comment by antoine-levitt** [comment]
I'm in favor (or favour? :-p) of harmonizing everything to US spelling

**Comment by mfherbst** [comment]
I'm in favour for UK spelling, but I think we already agreed to US spelling at some point. So let's just keep it?

**Comment by antoine-levitt** [comment]
OK then I'll pass it through a spellchecker and fix the remaining UK spellings (eg diagonalise)

**Comment by mfherbst** [comment]
Things like `diagonalize` or `symmetrize` really break my heart :cry:

**Comment by antoine-levitt** [comment]
FWIW I agree it's ugly, but it's standard, so...
