### ISSUE TITLE
dftk.org loop

### ISSUE THREAD

**Issue by zdroid** [JuliaMolSim/DFTK.jl#290]
This repository has dftk.org listed as its website, but that link then points back to this repository. Wouldn't it be better to point dftk.org to something like https://juliamolsim.github.io/DFTK.jl/dev/?

**Comment by antoine-levitt** [comment]
Hi and thanks for the interest! I kinda like DFTK.org to redirect to the github page (that's what i type in my browser to get here). The github page points to the docs, so I think it's fine to redirect here. We can also just remove the DFTK.org link if you think it's redundant.

**Comment by mfherbst** [comment]
I made the website to be [docs.dftk.org](docs.dftk.org). Than the loop is away and chances are people actually find the docs.

**Comment by zdroid** [comment]
@antoine-levitt @mfherbst Now that's great
