### ISSUE TITLE
Integrate with unitful in key constructors

### ISSUE THREAD

**Issue by mfherbst** [JuliaMolSim/DFTK.jl#297]
It probably would make life for setting up DFTK calculations a little easier if we integrated with Unitful in key constructors for quantities such as:
- Temperature
- Energy cutoff
- Lattice vectors
- Kgrid density

Continued discussion from #296

**Comment by mfherbst** [comment]
In theory one would need to use units on the convergence tolerances as well, but that might be pushing it a bit far, so I think that's it for now.

**Comment by jarvist** [comment]
Similarly it might be nice to have this optionally decorated onto the outputs. 
(I've spent far too much of my life trying to figure out whether compound units are constructed from Ha, Ry or eV and Bohr or Angstrom!)

**Comment by antoine-levitt** [comment]
This might be a bit much, as we'd need to do that everywhere (which is very annoying and technically tricky) or end up doing it on a case by case basis and therefore inconsistently. It's clearly documented that all outputs of DFTK are atomic units, so hopefully this should be clear. Maybe we can be extra explicit where we already do some pretty printing, eg here: https://github.com/JuliaMolSim/DFTK.jl/blob/master/src/energies.jl

**Comment by mfherbst** [comment]
I see your point and I have certainly felt that pain, too. Since we don't really have a proper stabilised "output" interface (or for that sake much printing / logging) for the moment, it's not yet completely clear how to do that and so I'd consider that to some extent lower priority compared to the input question.

**Comment by mfherbst** [comment]
> pretty printing, here: https://github.com/JuliaMolSim/DFTK.jl/blob/master/src/energies.jl

Where it's all hartree ... I'm not so sure that helps.

**Comment by antoine-levitt** [comment]
We can just have "Energy breakdown (Ha):"

**Comment by jarvist** [comment]
> I see your point and I have certainly felt that pain, too.

Just something I hope it is worth keeping in mind! 
I think it should be fairly pleasant to write something in Unitful. 

Once the DFTK package get's more complex, it will inevitably start to produce output in units beyond energy (you know, forces, spring constants, permittivity, frequencies, angular frequencies, etc.), and in other more established DFT codes you often find quite messy output functions that have an implicit understanding of the internal units, and usually some opaque magic number to convert to the output units. 
I think it's definitely worth thinking how to avoid this.

**Comment by antoine-levitt** [comment]
That I agree, if we want to use something else than atomic units at one point we should use Unitful.

**Comment by mfherbst** [comment]
Me too.
