### ISSUE TITLE
Simplistic checkpointing callback

### ISSUE THREAD

**Issue by mfherbst** [JuliaMolSim/DFTK.jl#298]
While we should probably wait until #75 and #33 are done to do checkpointing properly, at least a simplistic checkpointing (ρ and \psi) function using the callback mechanism could be quite useful.

**Comment by antoine-levitt** [comment]
Yes, we should do the scfres thing in https://github.com/JuliaMolSim/DFTK.jl/issues/75 and checkpoint on that
