### ISSUE TITLE
API Reference text issue

### ISSUE THREAD

**Issue by umbriquse** [JuliaMolSim/DFTK.jl#300]
For some of the functions in the API Reference page [https://juliamolsim.github.io/DFTK.jl/dev/api/](https://juliamolsim.github.io/DFTK.jl/dev/api/) the LATEX code is visible, making the formulas and some text pretty hard to read.

Some examples are: DFTK.HybridMixing, DFTK.Kinetic, and DFTK.RestaMixing

**Comment by mfherbst** [comment]
Hi @umbriquse Thanks for mentioning this, but as we say on the page the API reference is not intended to be clean or in any way structured. What you describe then just reflects this. Our philosophy is really to encourage people to look at the code, so we have not (and do not intend to) spend a lot of time into it. It's more a "take it as it is" sort of thing.

But of course we are more than happy for any PR cleaning up behind our mess!

**Comment by antoine-levitt** [comment]
We should maybe homogenize what we do in the comments though. I always get confused with the syntax... I tend to favor Unicode (nonlatex) for comments anyway since we read them along the code
