### ISSUE TITLE
Decide on r_to_G vs from_fourier().real

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaMolSim/DFTK.jl#311]
We do this at a bunch of places in the code. I'm fine with r_to_G but then we provide convenience functions accepting real input?

**Comment by mfherbst** [comment]
I don't mind that. I just find `from_fourier()` is for something else.

**Comment by antoine-levitt** [comment]
Actually they kind of serve different purposes. In particular the from_fourier API makes it explicit we're talking about a real quantity. r_to_G is kind of the low-level API. We should have a broader conversation as to what type of quantities we manipulate, on what grid/basis and what are the best data structures for that, so I'm closing this issue in favor of the one on RFAs.

**Comment by mfherbst** [comment]
Well that was kind of my point from the start, but I am not sure in the way we use the things at the moment is consistent with this separation. I think we should keep the issue open.

**Comment by mfherbst** [comment]
This is invalid after the refactoring. Now there is only one way.
