### ISSUE TITLE
Rethink RealFourierArray

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaMolSim/DFTK.jl#313]
There are a number of things we should rethink about RealFourierArrays. First the current design is intrinsically bad performance for hot loops because we have to look up the state (even if it doesn't change). Second we might want to represent things like currents and vector potentials, which have more than one component. Third, we always seem to be going back and forth between RFAs and their real/fourier components, so it doesn't feel that useful.

**Comment by antoine-levitt** [comment]
Possibly we could make more use of https://github.com/SciML/RecursiveArrayTools.jl, eg for the psi

**Comment by mfherbst** [comment]
Yes that might be a good idea. I am looking at the spin stuff at the moment and that could also be a case where having some higher-level structure for the different spin components could be helpful. Also for representing gradients of the density we are already running into a case with 3 or 9 (spin) components respectively.

We should keep in mind why we designed it in the first place, however, namely to avoid doing FFTs by doing them lazily. I think this is still a valid consideration and should be supported in whatever we replace it by.

**Comment by antoine-levitt** [comment]
I'm actually less and less convinced by the laziness argument. We basically always end up using both real and fourier components (otherwise we wouldn't store it in a RFA). Also since we don't use it for the psi it's less important for performance. So I'm not convinced it's worth the complexity it adds (type stability, thread safety, etc)

**Comment by mfherbst** [comment]
Ok, we should rethink more properly, but it's not just about speed. It's also about convenience (not needing to think whether the real/fourier component has already been computed or not).

**Comment by antoine-levitt** [comment]
Exactly: it's the laziness part I'm not too sure about. Might as well compute both from the get go. Spin is a very good point; the flexibility of the things in RecursiveArrayTools is interesting in that regard.

**Comment by antoine-levitt** [comment]
OK so here are some thoughts. We want to be able to represent quantities on the grid. Things we might want to represent:

- Densities: either scalars, 2-component or 2x2 matrices
- Potentials: either scalars or 2-component
- Magnetic potentials: 3-component
- Currents: 3-component

All these I think are real quantities, except for the 2x2 densities in the noncollinear case?

I'm less and less sure we should have a specific treatment for real and fourier. So I would do away with RFAs entirely, and just have the convention that everything is always passed in real space. If we need to optimize (which we probably shouldn't anyway) we can do that later as a hack (eg pass two arguments, or have a caching function). So bearing that in mind we have a number of possibilities:

- Separate for each component
- Arrays of arrays, eg `arr[ncomp][i1, i2, i3]`
- Multidimensional arrays, eg `arr[i1, i2, i3, ncomp]`
- Fancy arrays from that diffeq package

I think I would go with option 3, with the possibility to switch to option 4 later if we find that more convenient?

**Comment by antoine-levitt** [comment]
https://github.com/SciML/RecursiveArrayTools.jl is actually pretty nice. Possibly we can get rid of the pack/unpack routines in direct_minimization using that. That also seems like a good choice eg for magnetic fields, but less so for density where we'd want a structure with `rho.tot` and `rho.spin`. I did not find any good package for that.

**Comment by mfherbst** [comment]
I think we have to extend their stuff slightly. Also real/fourier is effectively a pair of these RecursiveArrayTools.jl thingies.

**Comment by antoine-levitt** [comment]
I think we can drop the real/fourier stuff provided we also make nice wrappers to be able to do `G_to_r(basis, rho_fourier)` where `rho_fourier` has fields `rho_fourier.tot` and `rho_fourier.spin`. Possibly we just need to make a Density struct that overloads the right stuff, but that seems a bit daunting.

**Comment by mfherbst** [comment]
I'm not so convinced about dropping real/fourier, but let's see.

**Comment by mfherbst** [comment]
Finally it is dropped :smile:.
