### ISSUE TITLE
Error from latest Libxc.jl

### ISSUE THREAD

**Issue by lancekavalsky** [JuliaMolSim/DFTK.jl#317]
Following up on discussion with @mfherbst 

When using the latest Libxc.jl I get the following error:

ERROR: LoadError: First axis for multidimensional rho array should be equal to the number of spin components (== 1)

**Comment by mfherbst** [comment]
I will "fix" it for now by putting a stricter upper bound on the Libxc version. We are currently in the process of refactoring XC stuff (in #187) to get collinear spin going. That will include the proper fix for this issue.
