### ISSUE TITLE
Data structure for `ρ` and `ρspin`

### ISSUE THREAD

**Issue by mfherbst** [JuliaMolSim/DFTK.jl#320]
`ρ` and `ρspin` occurr together all the time. They should really live in one data structure with access to `ρα`, `ρβ`, total, spin, etc.
Related to #313

**Comment by antoine-levitt** [comment]
An argument for having a plain-old-array data structure like rho[i,j,k,sigma] (rather than, say, a tuple): there's no way to make MPI communicate a tuple of arrays in one call. Maybe we're ending up being too complicated thinking about fancy types, and should stay fortran-style use arrays everywhere (possibly backed by helper functions)

**Comment by mfherbst** [comment]
I'm starting to get the same feeling from my recent dive into spin in fact.

**Comment by mfherbst** [comment]
I think what we want is https://github.com/SciML/LabelledArrays.jl

**Comment by antoine-levitt** [comment]
Not really suited for arrays of arrays it looks like? I think we need to go back to plain old multidimensional arrays (eg rho[i,j,k,ispin], A[i,j,k,alpha]) and minimize the array of arrays business. We can always have wrappers on top if we need.

**Comment by mfherbst** [comment]
If I understand right exactly this works with this LArrays data structure in the sense that array.α will return you a view on the α-slice of the array.

**Comment by antoine-levitt** [comment]
I see, I did not see that! It does indeed look nice, but 1) printing is not great 2) types get lost on operations:

```julia
julia> z = @LArray randn(2,2,2) (a = (:,:,1), b = (:,:,2));

julia> z
2×2×2 LArray{Float64,3,Array{Float64,3},(a = (Colon(), Colon(), 1), b = (Colon(), Colon(), 2))}:
[:, :, 1] =
 :a => 1.3592419963675093  …  :a => 0.07155526189523567
 :a => 1.3067288615693529     :a => 0.9627847168812409

[:, :, 2] =
 :b => -0.12513668476825365  …  :b => -0.3630301199122946
 :b => -0.8814833389669795      :b => -0.018224219379284038

julia> z + z
2×2×2 Array{Float64,3}:
[:, :, 1] =
 2.71848  0.143111
 2.61346  1.92557

[:, :, 2] =
 -0.250273  -0.72606
 -1.76297   -0.0364484

julia> 2z
2×2×2 Array{Float64,3}:
[:, :, 1] =
 2.71848  0.143111
 2.61346  1.92557

[:, :, 2] =
 -0.250273  -0.72606
 -1.76297   -0.0364484

julia> z .+ z
2×2×2 Array{Float64,3}:
[:, :, 1] =
 2.71848  0.143111
 2.61346  1.92557

[:, :, 2] =
 -0.250273  -0.72606
 -1.76297   -0.0364484
```
So not great...

**Comment by mfherbst** [comment]
Yeah ok, too bad, but maybe an ingredient to the solution.

**Comment by mfherbst** [comment]
Done as we dropped this idea in favour of plain arrays.
