### ISSUE TITLE
Implement nonlinear core correction

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaMolSim/DFTK.jl#335]
https://aip.scitation.org/doi/10.1063/1.4793260

**Comment by mfherbst** [comment]
And here is the data:
https://github.com/cp2k/cp2k/blob/master/data/NLCC_POTENTIALS

**Comment by antoine-levitt** [comment]
The important equations are (A5) and (A6). It's just adding an atomic-centered gaussian density to the density used in the XC term. Trivial to do, and should be OK with our terms interface.

**Comment by antoine-levitt** [comment]
Seems the NLCC is only useful for some elements though

**Comment by azadoks** [comment]
Also discussed in, #759 .

**Comment by mfherbst** [comment]
This is now done for UPF files and whenever PseudoPotentialIO provides NLCC.
