### ISSUE TITLE
Homogenize div

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaMolSim/DFTK.jl#346]
We have `floor(Int, n, m)`, `n÷m`, `div(n,m)` right now. I tend to use `div` but I have no strong preference with `÷`

**Comment by mfherbst** [comment]
I think we should use `n ÷ m` (with spaces around the operator :smile:). Sometimes I think using `floor` explicitly though is nice to e.g. contrast to `ceil` in a similar construct.

**Comment by antoine-levitt** [comment]
OK, I'll try to do it consistently (but I don't have an emacs shortcut for it so no promises :-p). I'll change it if I can be bothered in existing code.
