### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by mfherbst** [JuliaMolSim/DFTK.jl#357]
Somebody asked me about this by email. Do we plan to do it? What sort of timeline? FFTW, MPI, Libxc all support windows, so it should not be too hard to do it in DFTK as well.

**Comment by antoine-levitt** [comment]
We don't have anything linux or mac specific, do we? It doesn't work out of the box?

**Comment by mfherbst** [comment]
Never tried. Don't have a windows, but we could try in the CI.

**Comment by antoine-levitt** [comment]
Ask the guy who asks for it to try and report bugs. CI if I remember correctly we can't do in travis so we'd have to use a separate one...

**Comment by mfherbst** [comment]
> Ask the guy who asks for it to try and report bugs. 

Did

> CI if I remember correctly we can't do in travis so we'd have to use a separate one...

Not true. After github got native CI after the Microsoft takeover Travis had to diversify.

**Comment by antoine-levitt** [comment]
Cool, I did not know (both that github has native CI and that travis has windows). So it's just one line to add CI?

**Comment by mfherbst** [comment]
In theory, but in practice probably not (e.g. we need python packages).

**Comment by mfherbst** [comment]
CI for windows is prepared in #372. Turns out that support is not out of the box unfortunately. Amongst strange numpy issues one thing is the way we select and load pseudos. For us the identifier is "hgh/lda/something", which nicely maps to a path in linux but not in windows, so a few workarounds are probably needed for this. Leaving both things aside the core code seems to be working, however, so that the effort to get this going should be manageable. For now I still cannot be bothered.

**Comment by antoine-levitt** [comment]
Marking this as "good first issue": if someone wants this they should be able to implement it pretty easily.

**Comment by mfherbst** [comment]
Well ... modulo the numpy issue. Those are always nasty.
