### ISSUE TITLE
compute_forces_cart not found?

### ISSUE THREAD

**Issue by stur86** [JuliaMolSim/DFTK.jl#371]
I've just installed DFTK using `Pkg.add("DFTK")` on Julia 1.4.1. The version used is `v0.1.17`. When I try using the command `compute_forces_cart` after importing DFTK and using it to solve the first tutorial the symbol can not be found. DFTK has methods `compute_bands            compute_current           compute_density           compute_kernel            compute_partial_density!  compute_χ0` but not for forces. Is this a bug, or do I simply need to update to the master version?

**Comment by antoine-levitt** [comment]
Yes that's a recent addition, you need to update to the newest version (or we need to tag a new version). Try `add DFTK#master` at the Pkg command line.

**Comment by antoine-levitt** [comment]
Ah yes this is because the documentation points to the master version. Hm. The proper solution could be to have two links, to dev and stable version, but given we do release new versions relatively frequently, we might as well systematically tag new versions when we make doc changes? Or tell the users to always install master versions, since we are relatively careful not to break master...

**Comment by stur86** [comment]
Ok, thanks, will do. Yes, maybe the documentation should be a bit clearer. Also, when I try, I get `ERROR: `DFTK#master` is not a valid package name` so there might be another problem there.

**Comment by antoine-levitt** [comment]
Really? I just tried
```
(@v1.5) pkg> add FFTW#master
    Cloning git-repo `https://github.com/JuliaMath/FFTW.jl.git`
   Updating git-repo `https://github.com/JuliaMath/FFTW.jl.git`
   Updating registry at `~/.julia/registries/General`
######################################################################## 100.0%
  Resolving package versions...
Updating `~/.julia/environments/v1.5/Project.toml`
  [7a1cc6ca] ~ FFTW v1.2.4 ⇒ v1.2.4 `https://github.com/JuliaMath/FFTW.jl.git#master`
Updating `~/.julia/environments/v1.5/Manifest.toml`
  [7a1cc6ca] ~ FFTW v1.2.4 ⇒ v1.2.4 `https://github.com/JuliaMath/FFTW.jl.git#master`
```
Where does your error come from?

**Comment by mfherbst** [comment]
> The proper solution could be to have two links, to dev and stable version

Yes that's a good idea and not too hard to achieve.

> Or tell the users to always install master versions, since we are relatively careful not to break master...

I veto that and you know it :smile:

**Comment by antoine-levitt** [comment]
Can't blame me for trying ;-)

**Comment by stur86** [comment]
> Really? I just tried
> 
> ```
> (@v1.5) pkg> add FFTW#master
>     Cloning git-repo `https://github.com/JuliaMath/FFTW.jl.git`
>    Updating git-repo `https://github.com/JuliaMath/FFTW.jl.git`
>    Updating registry at `~/.julia/registries/General`
> ######################################################################## 100.0%
>   Resolving package versions...
> Updating `~/.julia/environments/v1.5/Project.toml`
>   [7a1cc6ca] ~ FFTW v1.2.4 ⇒ v1.2.4 `https://github.com/JuliaMath/FFTW.jl.git#master`
> Updating `~/.julia/environments/v1.5/Manifest.toml`
>   [7a1cc6ca] ~ FFTW v1.2.4 ⇒ v1.2.4 `https://github.com/JuliaMath/FFTW.jl.git#master`
> ```
> 
> Where does your error come from?

The error was me trying to use `Pkg.add("DFTK#master")` from the Julia interpreter instead of using the REPL. I'd suggest that that needs fixing in the documentation too! The # probably confuses the interpreter.

**Comment by mfherbst** [comment]
Ah yes, that's indeed a typo. The correct command is
```
Pkg.add("DFTK", rev="master")
```

**Comment by stur86** [comment]
Ok, one more thing then (though at this point this could be its own issue): when using the master version, I need to add `DFTK.` in front of each function and class, even after `import DFTK`. I suppose this has to do with the main script. Problem is, basically the code in the tutorial doesn't work as is for either approach - with the release version because of the forces, and with the master version because of this.

**Comment by antoine-levitt** [comment]
You have to use `using DFTK` (like with any other julia package) to get the names exported.

**Comment by antoine-levitt** [comment]
If there's a `import DFTK` in the docs it's a mistake

**Comment by mfherbst** [comment]
By the way ... docs and badge will be fixed in #372. Should go into master today.

**Comment by stur86** [comment]
> If there's a `import DFTK` in the docs it's a mistake

Sorry, yes, I realised my mistake afterwards, hence why I deleted my post. Didn't notice the difference between `using` and `import`. I'm a novice at Julia.

**Comment by antoine-levitt** [comment]
Ah I was confused because the post appeared, disappeared and re-appeared. No worries, it takes a while to get these julia idiosyncrasies, especially if you don't have a julia afficionado on hand.

**Comment by mfherbst** [comment]
Actually it is very confusing and subject to debate amongst the Julia community. You're not the first to fall into that trap @stur86 :smile:.

**Comment by antoine-levitt** [comment]
Yeah I agree it's a bit annoying. Back when I started julia there was even `importall` which was even more confusing. Now I just always use `using`...
