### ISSUE TITLE
Performance audit

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaMolSim/DFTK.jl#38]
The following are non-FFT hotspots when running silicon with a large-ish ecut:

- compute_density
- the logic around mul!(Y,block,X) which should allocate less and fuse more. one alloc is easily dealt with, but we might want to represent the kinetic as simply an array to get it to also fuse  some of the linear algebra in lobpcg

Also we do a lot more iterations than necessary of the eigensolver; setting maxiter to 4 gave a good speedup.

This is representative of problems with a small unit cell. Should benchmark large unit cells now.

**Comment by mfherbst** [comment]
I'm happy to do that, but I'd say the result will be disappointing at first ...

**Comment by antoine-levitt** [comment]
Sure? I don't see anything apart from the above that could explain a difference, so it's clear where to go to catch up with other codes, and not that hard. Abinit has options to print timings, so we could eg get the total number of FFTs they do and compare.

**Comment by antoine-levitt** [comment]
OK so I benchmarked DFTK against abinit for a very simple testcase. Ecut 50, LDA, temperature 0.01, Silicon with no kpoint, box with lattice constant a=20 (reduced position of atoms rescaled to be physical). We took 44s, abinit took 8s. I did not do any fine tuning either in abinit (just took source, made ./configure && make, and took the source of the example; I did add in FFTW, but that didn't change the timings much) or DFTK (I did specify a maximum of 4 iterations for LOBPCG, to match abinit's choice). That's not too bad! Pretty sure with a reasonable amount of work we can get to at least within a factor of 2, and possibly beat them.

I couldn't make abinit to use multithreaded, so I disabled all threading in DFTK. Turning it on yielded 34s, which is not great (ie we can probably do better by explicitly threading the FFTs)

**Comment by mfherbst** [comment]
Hmm 44s to 34s indeed sounds pretty bad for me as well, but the ballpark of 44 (DFTK) versus 8 (ABINIT) sounds familiar from my experiments.

**Comment by mfherbst** [comment]
Just to keep track of things todo: In #44 the `zeros` function was discussed as an alternative to our current `array = similar(data), array .= 0` pattern. This requires https://github.com/JuliaLang/julia/issues/130.

**Comment by mfherbst** [comment]
We have worked quite a bit on this stuff recently. Any objections against closing it for now? I think the low-hanging fruits discussed here are kind of done now.

**Comment by antoine-levitt** [comment]
Sure. We can rebenchmark later on, but the results above might be obsolete now.
