### ISSUE TITLE
New folder for research codes?

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaMolSim/DFTK.jl#381]
I'm doing eg stuff for the anyons project, and the code probably going to come out as a relatively nice ~200loc file. Similarly other projects (like Gaspard's stuff, or our SCF/a posteriori things) end up being relatively manageable files that are too big for examples. It would maybe be nice to have them in the DFTK repo? I'm thinking we could have a "research/" repo where we put the code for published papers. Maybe once in a while we even run the code on them to check we haven't broken too much stuff in the meantime, and if we feel like it we can even fix them. It's a light, optional maintenance burden, it can help others build their own stuff, and it decreases the chance the code gets lost. Thoughts?

**Comment by mfherbst** [comment]
I'm not so sure about this. In fact actually the way we have been doing it now is even better: For the LDOS and the error paper we made two repositories, which are completely self-contained (own Manifest, Project, setup). That way it ensures that the code cannot only be looked at in 5 years, but also be run in 5 years ... and they also serve as inspiration for others.

I understand that for smaller cases that might not be worth it, but then these codes should still not live in here. We can make a separate repo for this purpose, though if you want.

**Comment by antoine-levitt** [comment]
I just like the idea of having a "central" repository of codes that use DFTK. What you suggest is a very good idea! Then we link to it from somewhere in the docs.

**Comment by mfherbst** [comment]
Exactly. That would have been my idea.
