### ISSUE TITLE
Possibility to "unfold" the k grid

### ISSUE THREAD

**Issue by LaurentVidal95** [JuliaMolSim/DFTK.jl#382]
The DFTK - Wannier90 interface pointed out that it could be useful to be able to "unfold" the k-grid, that is to retrieve the full range of k-point from a reduced by symmetry k-grid. For now, any scf calculation that serves as a basis for the production of Wannier functions have to be run with a full size k-grid.

**Comment by antoine-levitt** [comment]
Would be helpful to have a more formalized scfres for this also (we could have `unfold(scfres::ScfRes)` and `unfold(basis)`. For this we probably need to change the pwbasis interface a bit also to have the full kgrid information (which you also wanted, right?)

**Comment by antoine-levitt** [comment]
all the heavy lifting and annoyances regarding symmetries is already done and tested in apply_ksymop so hopefully no real trouble, "just" API work

**Comment by mfherbst** [comment]
Ähm maybe I misunderstand, but is not 

https://github.com/JuliaMolSim/DFTK.jl/blob/master/src/PlaneWaveBasis.jl#L478-L497

doing exactly what you want?

**Comment by antoine-levitt** [comment]
Forgot we had this! So we just need to write an unfold_scfres that combines this with the apply_ksymop and we're good to go

**Comment by antoine-levitt** [comment]
API-wise we can eg have two methods `unfold_symmetries(basis::PlaneWaveBasis)` (the current PlaneWaveBasis) and `unfold_symmetries(scfres)`? I know we discussed this at one point but can't remember where we landed

**Comment by mfherbst** [comment]
> Forgot we had this!

See and this is why you need searchable API documentation at docs.dftk.org.

I favoured the version you are proposing now, but you favoured the version we have now. So I'm happy to switch. Also `unfold_symmetries` is not such a bad name.

**Comment by antoine-levitt** [comment]
> I favoured the version you are proposing now, but you favoured the version we have now. So I'm happy to switch

I'm sensing a pattern here and in other threads... :-) I do think it makes a lot of sense to not anticipate too much on the future, and do things when we need them and not before, but I'll admit to a certain amount of laziness ;-)

**Comment by mfherbst** [comment]
Sure, but in retrospect I'm more often happy we don't agree on everything and fight a bit until we settle down :smile:.

**Comment by antoine-levitt** [comment]
Currently being done by @LaurentVidal95, Laurent you can mark this issue as closed when you're done :-)

**Comment by LaurentVidal95** [comment]
Hello, I may be mistaken but I'm using the "unfold_bz" routine that Michael must have implemented a while ago, which applies to both `basis` and `scfres` ! Do we need something else ? Otherwise I close this issue ! :)

**Comment by LaurentVidal95** [comment]
Hello, I may be mistaken but I'm using the "unfold_bz" routine that Michael must have implemented a while ago, which applies to both `basis` and `scfres` ! Do we need something else ? Otherwise I close this issue ! :)

**Comment by antoine-levitt** [comment]
Sorry I confused the unfold and the supercelling!
