### ISSUE TITLE
Add backref to basis from kpoint

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaMolSim/DFTK.jl#384]
And simplify a lot of functions that take as input basis and kpoint to just take kpoint

**Comment by antoine-levitt** [comment]
I've taken a look at this and the only problem I have is kpoints and pwbasis are both immutable, so can't have a reference to each other (chicken and egg thing). So we have to give up on mutability of one (or both) of them. I'm pretty sure the performance impact is negligible.

**Comment by mfherbst** [comment]
And the issues start appearing ... yes indeed. There is no way around giving that up.

**Comment by antoine-levitt** [comment]
We already have some gymnastics to work around immutability of pwbasis (eg at the end of the pwbasis constructor)

**Comment by antoine-levitt** [comment]
So I enthusiastically got to work on this, but... https://github.com/JuliaLang/julia/issues/269. So that kind of settles it for now.

**Comment by mfherbst** [comment]
Yeah ... that's exactly the sort of stuff I was fearing. Well at least there are attempts and one day it will be done, I suppose.

**Comment by antoine-levitt** [comment]
I tried to figure out an alternative design that would still allow us to do things like `G_to_r(kpoint, psi)` but no luck. Possibly we could do something like https://github.com/JuliaMolSim/DFTK.jl/issues/97 and have basis contain a square_basis and kpoints, both of which would be subtypes of AbstractBasis... but this is probably pushing it too much.
