### ISSUE TITLE
Integrate with Xtals.jl

### ISSUE THREAD

**Issue by mfherbst** [JuliaMolSim/DFTK.jl#389]
A good candidate to integrate with for setting up calculations would be [Xtals.jl](https://simonensemble.github.io/Xtals.jl/dev).

**Comment by antoine-levitt** [comment]
Looks pretty barebones compared to ase

**Comment by mfherbst** [comment]
Sure, but would be a pure-Julia solution.

**Comment by Dsantra92** [comment]
Can I work on it?

**Comment by mfherbst** [comment]
Sure, you can give it a shot, but honestly I have no clue how it turns out to work. Especially I had this in mind as an option to replace the `atoms` / `magnetic_moments` arrays in DFTK by a "proper data structure". That might even require sensible extension in Xtals.jl itself, but feel free to try and see how it goes.

**Comment by Dsantra92** [comment]
I don't think this was a good idea. Xtals.jl is still in it's infant stage and requires lot of functionalities to replace the python package. I coded some of them over few weeks but I  am of the opinion that adding this bulk of code will not particularly help us here.

**Comment by mfherbst** [comment]
Hi @Dsantra92 thanks for reporting back. I have also come to believe that the better route is to work on a small standalone package just for the atoms data instead.

I'll close this for now. We can always reconsider at a later point.
