### ISSUE TITLE
Define and use cis2pi

### ISSUE THREAD

**Issue by mfherbst** [JuliaMolSim/DFTK.jl#400]
Just had a look through the release notes for 1.6 (which will be LTS).

Things worth using in DFTK once we move to 1.6 are:
- `sincospi`
- `cispi`

**Comment by antoine-levitt** [comment]
I'd rather not, cispi(2x) looks weird. These functions are used for accuracy not speed, and there's no need for better than usual accuracy in our case

**Comment by mfherbst** [comment]
Weirder than `cis(2T(π) * stuff)` ? Would be nice to get rid of the `T(...)` in many places.

**Comment by antoine-levitt** [comment]
Good point on the T(pi)... in that case we might want to define a cis2pi?

**Comment by mfherbst** [comment]
Yeah. That's a pretty good idea.
