### ISSUE TITLE
Allowed Extensions for load_psp()

### ISSUE THREAD

**Issue by umbriquse** [JuliaMolSim/DFTK.jl#407]
Would you be able to add the ".pspnc" extension to the load_psp() function?

**Comment by antoine-levitt** [comment]
Sure, when we have another library of pseudos we can just adapt the load_psp function. In the meantime, you can just load the pseudo manually by defining a parse_pspnc_file, giving it the full path, and giving the result to ElementPsp.

**Comment by umbriquse** [comment]
Yea, that was what I figured I had to do.

**Comment by mfherbst** [comment]
Yes that was exactly the intention of https://github.com/JuliaMolSim/DFTK.jl/blob/master/src/pseudo/load_psp.jl#L16--L21. Feel free to add your hook there as well.

**Comment by mfherbst** [comment]
I think the question has been answered. Feel free to reopen if needed.
