### ISSUE TITLE
Pymatgen namespaces change v2022.0.0

### ISSUE THREAD

**Issue by niklasschmitz** [JuliaMolSim/DFTK.jl#418]
Pymatgen has recently re-structured its namespaces, which is a breaking change for python imports like 
```python 
from pymatgen import Lattice  # now "from pymatgen.core.lattice import Lattice"
```
which might affect the `pyimport` statements in the interfaces.

[pymatgen v2022.0.0 breaking changes](https://pymatgen.org/compatibility.html#v2022-0-0)

**Comment by mfherbst** [comment]
Yikes. Thanks for the info. Yes indeed this will break basically all the pymatgen-related functionality.

I'd suggest to port the examples to the newest pymatgen, add a note to the installation info and either also port the DFTK interface completely or alternatively (if the effort is manageable) support both old and new interface.

All the related pymatgen interface code is https://github.com/JuliaMolSim/DFTK.jl/blob/master/src/external/pymatgen.jl and https://github.com/JuliaMolSim/DFTK.jl/blob/master/src/external/load_from_python.jl. Potentially also https://github.com/JuliaMolSim/DFTK.jl/blob/master/src/postprocess/band_structure.jl is affected.

I'm quite busy lately, but of course happy to review a PR fixing this :smile:.

**Comment by antoine-levitt** [comment]
> v2022.0.0

What, did I sleep for a year?

**Comment by antoine-levitt** [comment]
It's basically just the import statements that need modifying so that should be OK. If I understand correctly they just want us to use more qualified names so the new import statements should also be backward compatible?
