### ISSUE TITLE
Remove using GenericLinearAlgebra warning when GenericLinearAlgebra is already defined

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaMolSim/DFTK.jl#429]
Can probably use `@isdefined`

**Comment by mfherbst** [comment]
no that comes from something else. You need to actually remove the `using Pkg` on things you load with requires once `Pkg` becomes available as requires does the `using` automatically.

**Comment by mfherbst** [comment]
I thought I caught all these cases a while ago.

**Comment by mfherbst** [comment]
Ah sorry my bad. I got your comment now.
