### ISSUE TITLE
Implement conversions between grids

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaMolSim/DFTK.jl#43]
Something that would be quite useful is to be able to convert quantities (densities, wavefunctions) between grids (different lattices, different ecuts, different fft_sizes). Eg a more generalized version of `interpolate_at_kpoint`. Doesn't need to be accurate.

**Comment by mfherbst** [comment]
Absolutely! I thought about having more or less a hierarchy of methods (kpoints, then full plane wave grids then lattices).

**Comment by antoine-levitt** [comment]
Can we close this are there conversion methods still needed? @gkemlin

**Comment by mfherbst** [comment]
I think we have a good first set. I'll close this for now.
