### ISSUE TITLE
Documentation for spin not up to date

### ISSUE THREAD

**Issue by gkemlin** [JuliaMolSim/DFTK.jl#436]
The documentation of this example https://juliamolsim.github.io/DFTK.jl/stable/examples/collinear_magnetism/ is not up to date : 
it displays
```
ρspin  = guess_spin_density(basis, magnetic_moments)
scfres = self_consistent_field(basis, tol=1e-6, ρspin=ρspin, mixing=KerkerMixing())
```
instead of
```
ρ0 = guess_density(basis, magnetic_moments)
scfres = self_consistent_field(basis, tol=1e-6; ρ=ρ0, mixing=KerkerMixing())
```

**Comment by mfherbst** [comment]
You need to go to the dev docs: https://juliamolsim.github.io/DFTK.jl/dev/examples/collinear_magnetism/
