### ISSUE TITLE
Binder tutorial issue

### ISSUE THREAD

**Issue by louisponet** [JuliaMolSim/DFTK.jl#448]
After clicking the binder badge on the tutorial page, executing the first cell complains that Plots is not installed.

**Comment by mfherbst** [comment]
Ups ... thanks for letting us know. I'll fix that right away.

**Comment by mfherbst** [comment]
Still not working due to some dependency issue unfortunately.

**Comment by mfherbst** [comment]
Seems to work now: https://mybinder.org/v2/gh/JuliaMolSim/DFTK.jl/gh-pages?filepath=v0.3.2/guide/tutorial.ipynb
