### ISSUE TITLE
Fix and document conventions for response-like computations

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaMolSim/DFTK.jl#460]
First and easy part: we should use δx (and not dx) consistently for a variation in x.

We manipulate two kinds of response operators: two-point Op(r1,r2) mapping potentials to densities or vice versa, and four-point Op(r1, r1', r2, r2') mapping hamiltonians to density matrices or vice versa. The latter we only manipulate indirectly by their actions on ψ (for hamiltonians) or δψ (for density matrices).

It'd be good to use more consistent notations, in particular for the 2pt vs 4pt functions, and use them consistently (in papers and code). The notations below use the suffix hat consistently for 4point versions. it's not great and definitely not standard, but I don't have any better ideas right now.

Two-point operators:
K, the derivative of the Hartree-exchange-correlation potential wrt the density, and its components vc and Kxc (δρ -> δV)
χ0, the independent-particle susceptibility (δV -> δρ)
χ, the self-consistent susceptibility (δV -> δρ)
ε, the dielectric operator (δV -> δV)

Four-point operators:
Ωhat, the hessian (δP -> δH)
Lhat, the Liouvillian, which we don't use so much but is important eg for TDDFT (δP -> δH)
Khat, the four-point version of the above (δP -> δH)
χ0hat, the independent-particle 4-point susceptibility (δH -> δP)
χhat, the self-consistent 4-point susceptibility (δH -> δP)
εhat, the 4-point dielectric operator (δH -> δH)

In our paper with Gaspard and Eric, we call Ωhat just Ω, and Khat just K.

Thoughts?

**Comment by mfherbst** [comment]
Actually I like that notation. I would say we give that a go and rethink in case we find more trouble later.

**Comment by mfherbst** [comment]
Regarding notation: That feels like something which should go to the advanced section of the DFTK documentation (like the symmetries stuff).

**Comment by antoine-levitt** [comment]
Suggestion after discussion with Gaspard: 
- In papers we use bold
- In comments where we need to clarify we use 2p/4p, eg "χ02p = -R Ω4P^-1 E"
- In code, we don't necessarily need to clarify, and there's also an additional complication that we apply them to orbitals, so we do not specify (eg `apply_Ω`)

**Comment by mfherbst** [comment]
> In comments where we need to clarify we use 2p/4p, eg "χ02p = -R Ω4P^-1 E"

This looks ugly and a bit confusing. Can we at least use subscripts?

**Comment by antoine-levitt** [comment]
You mean unicode sub/superscripts? I'm not used to that but yes sure

**Comment by antoine-levitt** [comment]
\_1 TAB

**Comment by antoine-levitt** [comment]
(in julia REPL)

**Comment by mfherbst** [comment]
yes unicode superscripts indeed

**Comment by antoine-levitt** [comment]
OK, let's go with that. Let's wait until we've made the needed modifications in the code and pushed the linesearch paper to put it in the DFTK docs

**Comment by mfherbst** [comment]
Agree.
