### ISSUE TITLE
Segfault in 1.7

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaMolSim/DFTK.jl#480]
https://github.com/JuliaMolSim/DFTK.jl/runs/3035339708?check_suite_focus=true
I can reproduce locally
(for some reason CI still has a green checkmark)

**Comment by antoine-levitt** [comment]
For more fun it only happens when running the tests, not julia silicon_lda.jl

**Comment by antoine-levitt** [comment]
julia -e 'using DFTK; setup_threading(); include("silicon_lda.jl")' doesn't trigger

**Comment by antoine-levitt** [comment]
OK, julia -e 'using DFTK; include("hydrogen_all_electron.jl"); include("silicon_lda.jl")' does. Really not sure what's going on here, I'll raise it on the julia repo, unless you have a better idea @mfherbst ?

**Comment by mfherbst** [comment]
> (for some reason CI still has a green checkmark)

because issues in nightly are ignored.

Could have to do with JLD2. There is an issue on that and we need the older version due to MPI stuff. You could try to run it in an environment without JLD2 to check that. Otherwise I don't have a good idea at the moment.

**Comment by antoine-levitt** [comment]
Why would it involve JLD? These tests don't call it

**Comment by mfherbst** [comment]
wild guess, since it's a segfault?

**Comment by antoine-levitt** [comment]
> because issues in nightly are ignored.

Could you make it like coverage? Red cross when fails, but doesn't block the merge?

**Comment by mfherbst** [comment]
It was like this with travis, but gha did not support this easily last time I tried. Essentially you would have to have two job scripts with duplicate code to make that work. But maybe there is something more clever now. I'll take a look.

**Comment by antoine-levitt** [comment]
OK, it was just in case it was easy, don't bother

**Comment by mfherbst** [comment]
ok.

**Comment by mfherbst** [comment]
@antoine-levitt Did you try rerunning your session with this nice ["backwards-in-time" debug tool](https://julialang.org/blog/2020/05/rr/) Keno made some time ago. I think the flag is `--bug-report`

**Comment by antoine-levitt** [comment]
I just tried, but it just crashed without uploading a bug report (it looked like it worked fine when exiting the session normally)

**Comment by mfherbst** [comment]
The fix is now merged upstream.

**Comment by antoine-levitt** [comment]
I'll test it in the next beta

**Comment by antoine-levitt** [comment]
Should be fixed now on master, I'll test it on a nightly when I get time

**Comment by antoine-levitt** [comment]
Fixed
