### ISSUE TITLE
Stresses: API and symmetries

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaMolSim/DFTK.jl#484]
We should have an API for stresses, similar to that for forces

I think our current implementation is buggy in the case of symmetries. Worse, it might *look* like it is correct because it will match finite differences with a step size small enough that it is accepted by the tolerances on the symmetries. We should either think about it, or unfolding the BZ prior to computing the stresses. Unfolding seems easier :-)

**Comment by mfherbst** [comment]
Could be worth taking a strange cell and doing the calculation in both DFTK and a reference to have something to help deduce factors, I guess.
