### ISSUE TITLE
Windows CI started failing

### ISSUE THREAD

**Issue by mfherbst** [JuliaMolSim/DFTK.jl#501]
Could be a temporary issue or something more severe, but the Windows CI started failing to something pymatgen-related.

**Comment by antoine-levitt** [comment]
pymatgen.core.structure was imported properly but pymatgen.symmetry.bandstructure was not. Did they change their API? Hopefully pymatgen will be gone soon anyway.

**Comment by antoine-levitt** [comment]
Ah no sorry, the actual error is `cannot import name 'gcd' from 'fractions'`. So... broken python?

**Comment by antoine-levitt** [comment]
https://stackoverflow.com/questions/66174862/import-error-cant-import-name-gcd-from-fractions

**Comment by mfherbst** [comment]
Ähm ... ok, so not our problem I guess?

**Comment by antoine-levitt** [comment]
Yeah. Hopefully pymatgen will start requiring a less broken version of networkx

**Comment by mfherbst** [comment]
I wonder why this only happens on windows ...

**Comment by mfherbst** [comment]
I'm closing this for now, because it seems to be fixed magically ...

**Comment by antoine-levitt** [comment]
Best way to fix ci issues!
