### ISSUE TITLE
Fix AD for small occupations

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaMolSim/DFTK.jl#514]
See https://github.com/JuliaMolSim/DFTK.jl/pull/513#event-5159480887. Currently only done for Fermi-Dirac, should be done for other smearing types. Probably simplest to not define rules but have the function return 0 at overflows.

**Comment by niklasschmitz** [comment]
Also for Fermi-Dirac, the current fix is only sufficient for first order, as second order derivatives for large x again run into Inf/Inf division NaNs:
```julia
using DFTK, ForwardDiff
f0(x) = Smearing.occupation(Smearing.FermiDirac(), x)
f1(x) = ForwardDiff.derivative(f0, x)
f2(x) = ForwardDiff.derivative(f1, x)

x = 400.0
f0(x), f1(x), f2(x)  # (1.9151695967140057e-174, -0.0, NaN)
```

**Comment by antoine-levitt** [comment]
We should just hardcode 0/1 when overflow/underflow, which would remove the need for the ugly workaround in forwarddiff_rules?

**Comment by mfherbst** [comment]
Sounds fair and make physical sense.

**Comment by niklasschmitz** [comment]
That would simplify things for sure. As mentioned to me by @azadoks, that's also what QE does here specifying the `maxarg` to the exponential https://github.com/QEF/q-e/blob/6e083f7950e599a1a6788f0638610f88c1613670/Modules/wgauss.f90#L49. I can set up a small PR

**Comment by antoine-levitt** [comment]
We have `    max_exp_arg = -log(eps(T)) + 5  # add some wiggle room` in ewald, which sounds sensible.

**Comment by antoine-levitt** [comment]
Cute trick, let's go with that! (maybe `y = exp(x); y/(1+y)`? is the compiler sufficiently clever to recognize `exp` is pure?)

**Comment by niklasschmitz** [comment]
Checking the [optimized LLVM](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:julia,selection:(endColumn:1,endLineNumber:6,positionColumn:1,positionLineNumber:6,selectionStartColumn:1,selectionStartLineNumber:6,startColumn:1,startLineNumber:6),source:'function+f(x)%0A++++return+exp(-x)+/+(1+%2B+exp(-x))%0Aend%0A%0Aprecompile(f,+(Float64,))%0A'),l:'5',n:'0',o:'Julia+source+%231',t:'0')),k:50,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:julia_1_10_0,filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1',verboseDemangling:'0'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:julia,libs:!(),options:'',overrides:!(),selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+Julia+1.10.0+(Editor+%231)',t:'0')),k:50,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4) for Float64 it indeed does it automatically with only one exp, but to be sure (for Duals etc) I'll make it explicit :)
