### ISSUE TITLE
Segfault in preconditioning

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaMolSim/DFTK.jl#529]
Just remembered there was a problem with this and wanted to create an issue so we don't forget. @gkemlin can you post more details?

**Comment by mfherbst** [comment]
Ok ... interesting. In which preconditioner? SCF or diagonalisation?

**Comment by antoine-levitt** [comment]
Is this with MPI or not? Does adding GC.gc() increase the frequency of the bug?

**Comment by mfherbst** [comment]
Since @gkemlin uses threads, he does not use MPI.

But as a side note: You should use MPI. With threads the scaling in DFTK is very bad at the moment. I would bet your calculations are actually even *faster* if you only use 8 threads instead of 32.

**Comment by gkemlin** [comment]
Is juliampi install on the cluster ? This is why I used Threads ^^" I'm not aware about the scaling though, I can change that.

@antoine-levitt I try with GC.gc() and I tell you.
