### ISSUE TITLE
Move to JuliaMolSim

### ISSUE THREAD

**Issue by cortner** [JuliaMolSim/DFTK.jl#53]
Any chance I can convince you to move over to `JuliaMolSim` and register the package in the `MolSim` registry? Once we start using it, it would be very  helpful to have some minimal versioning information. Even without any expectation of backward compatibility - I generally  refuse to guarantee that.

**Comment by cortner** [comment]
I'm happy to help with any package manager / registry issues you might have...

**Comment by antoine-levitt** [comment]
We're going to move over to JuliaMolSim. Was the transition painful? Did you just tell people to change their git remote?

Re the registry, we're a bit reluctant to do a release now - we want to clean things up and make a proper release, but it'll probably take another month or so. But if you just need a tag then we can probably do that? (I'm not very familiar with how that works...)

**Comment by cortner** [comment]
As long as you don’t register a release there is nothing to do really - github just forwards the links

**Comment by cortner** [comment]
Re registry- sure sounds sensible. But reconsider it. I used to be extremely reluctant as well. But the point of having a separate registry means we don’t have to follow very high standards. In fact you can register your package in both MolSim and General and have only high quality releases in General. Also the point of semver is to lower the barrier to creating new releases as frequently as necessary.

**Comment by cortner** [comment]
Actually moving the repo is a 23s process.

**Comment by mfherbst** [comment]
@cortner One more thing: Before the move, could  Beforehand could you just reassure I have sufficient permissions to quickly set up the attached services (Travis, coveralls etc.) at the organisation level ... I recall from a different project, that github's permission system is quite a bit more involved compared to single repos and I do not want to get locked out :smile:.

**Comment by mfherbst** [comment]
Oh and regarding the release ... we agreed to release a `0.0.1` to MolSim next week

**Comment by cortner** [comment]
I can just give you admin access - Antoine already has that as well.

**Comment by cortner** [comment]
Re release: once you start using your code for projects rather than as a project for its own sake you will really see the benefit! And just feel free to make 0.0.x increments arbitrarily breaking.

**Comment by mfherbst** [comment]
Perfect thanks very much ... I'll try to get it on asap.

**Comment by mfherbst** [comment]
Done now.
