### ISSUE TITLE
Kinetic Terms

### ISSUE THREAD

**Issue by cw-tan** [JuliaMolSim/DFTK.jl#538]
Hi, I'm pretty new to Julia and DFTK but I was hoping to use DFTK for orbital-free benchmarking. I scanned through the documentation but wasn't sure if it had what I wanted. 

After getting the results from a self-consistent field calculation, is there a way to access the positive-definite kinetic energy density as defined [here](https://juliamolsim.github.io/DFTK.jl/dev/api/#DFTK.Kinetic), the kinetic energy contribution to the stress, and the Kohn-Sham potential? Thank you!

**Comment by antoine-levitt** [comment]
Hi and thanks for your interest!

- The kinetic energy density you can compute it rather easily from the orbitals. See eg https://github.com/JuliaMolSim/DFTK.jl/blob/master/src/postprocess/current.jl for a related computation. If you do code it up please contribute it to this package, it could be useful to other people (eg for meta-GGAs)!
- The kinetic contribution to the stress you can get by only keeping the Kinetic term in the new_model here: https://github.com/JuliaMolSim/DFTK.jl/blob/master/src/postprocess/stresses.jl
- The Kohn-Sham potential we have, it's the function total_local_potential(ham::Hamiltonian) defined here: https://github.com/JuliaMolSim/DFTK.jl/blob/master/src/terms/Hamiltonian.jl

All of this should be relatively easy, but you do have to look at the code a bit. The examples should help you get the structure. If you're stuck let us know and we can help.

May I ask what you want to do exactly? There's an open issue for Thomas-Fermi here: https://github.com/JuliaMolSim/DFTK.jl/issues/122

**Comment by antoine-levitt** [comment]
Or for the stresses, even simpler: just change the energies.total line in compute_stresses to energies.kinetic

**Comment by cw-tan** [comment]
Great, thanks! I literally installed Julia yesterday but I'm eager to have a go at it! I'm just hoping to inspect these quantities from Kohn-Sham DFT to possibly give some insight for the development of kinetic energy functional approximations.

**Comment by antoine-levitt** [comment]
OK, happy discovery :-) I'm closing the issue for bookkeeping purposes, feel free to ask for help, here or on slack.
