### ISSUE TITLE
Atomic positions in cartesian coordinates

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaMolSim/DFTK.jl#546]
It's often useful to specify atomic positions in cartesian coordinates. We could maybe have something like
```julia
struct CartesianAtomicPositions
    atoms
end
to_relative_coordinates(atoms::Any, lattice) = atoms
to_relative_coordinates(c::CartesianAtomicPositions, lattice) = [(el, [lattice\p for p in pos]) for (el, pos) in c.atoms
```
and then do atoms = to_relative_coordinates(atoms) in Model?

**Comment by mfherbst** [comment]
This will be "solved" once we implement the interface to AtomsBase (which I will do soon) which is supposed to deliver such things once and for all for the full julia ecosystem.

**Comment by antoine-levitt** [comment]
OK I wondered about that. Closing!
