### ISSUE TITLE
Make perturbation-based error bounds available in master

### ISSUE THREAD

**Issue by mfherbst** [JuliaMolSim/DFTK.jl#560]
As briefly discussed offline with @gkemlin, we should get the implementation discussed in https://arxiv.org/abs/2111.01470 up to speed and readily available for use in DFTK. Of course let's not worry too much about the details such as performance initially.

@gkemlin Where is the code currently located? How close is it to being mergeable? If I recall correcty most aspects (grid transfer, newton solver etc.) are anyway already available, right?

**Comment by antoine-levitt** [comment]
We discussed with Gaspard, a good way to do this at least now is as an example

**Comment by antoine-levitt** [comment]
I'm kind of reluctant to have it as a black-box thing without more extensive testing. But if we have plenty of caveats then we can possibly do that yeah

**Comment by gkemlin** [comment]
At the moment, the files are located on my computer. I had a branch called "estimators" that I cleaned and I think can be removed cause I don't really remember what I modified on it. And then can open a new branch to merge it with master. 

I think an example file following what we do in the paper can be easily generated at the moment (which would be great also to include a link in the paper after its review before publishing it).

To include it as a ready-to-use function, we should think about what we want : use it as an error estimator ? a way to compute more precise forces ?

**Comment by gkemlin** [comment]
(An example file for silicon would be no more than few dozens of lines)

**Comment by mfherbst** [comment]
> I'm kind of reluctant to have it as a black-box thing without more extensive testing.

Ok, that makes sense.

> I think can be removed  

done

>  use it as an error estimator ? a way to compute more precise forces ?

Well ideally both. One sort of includes the other, no?

But ok, I'm convinced. Let's have it as an example with a link to the paper first. @gkemlin When you make the PR can you also take a quick pass at https://docs.dftk.org/stable/publications/ to see if it's up to date.

**Comment by mfherbst** [comment]
Silicon is a bit boring. If it's not too expensive, can you go for the TiO2?

**Comment by gkemlin** [comment]
Yes of course ! Do we do that for one couple (Ecut, Ecut_ref) or do we seek to plot a figure like Figure 9 in https://arxiv.org/pdf/2111.01470.pdf ? Generating the whole figure takes time, I would rather aim to a well chosen couple to see the effectiveness of the bound.

I'll try to propose you something in the coming week then :-)

> Well ideally both. One sort of includes the other, no?
Yes, true, the question is more about the output we want but it's not a big issue.

> When you make the PR can you also take a quick pass at https://docs.dftk.org/stable/publications/ to see if it's up to date.
What appears online now seems to be up to date.

**Comment by mfherbst** [comment]
>  I would rather aim to a well chosen couple to see the effectiveness of the bound.

Sounds good to me. Otherwise it probably gets too expensive. 

> What appears online now seems to be up to date.

ok, never mind then :smile:.

**Comment by mfherbst** [comment]
Closing as PR is merged.
