### ISSUE TITLE
Dynamically adjust number of targeted bands in SCF

### ISSUE THREAD

**Issue by mfherbst** [JuliaMolSim/DFTK.jl#562]
As it says, move away from keeping `n_bands` fixed during the SCF.

**Comment by antoine-levitt** [comment]
See discussion in https://github.com/JuliaMolSim/DFTK.jl/pull/561#discussion_r783758938

**Comment by mfherbst** [comment]
Also while one is on it, remove the constraint that the number of bands is identical in each k-Point.
