### ISSUE TITLE
Struct for `composition`?

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaMolSim/DFTK.jl#57]
We pass around `composition` a lot and end up documenting it in several places. Should we just give it a struct?

**Comment by mfherbst** [comment]
That's not a bad idea. I thought about it before and wanted to leave it until we see more clearly how we need it.

One advantage would be that it would be easier to hide some `pymatgen` details for things such as doubling the unit cell for supercell sampling, which is definitely something we'll be using a lot more in the future.

**Comment by antoine-levitt** [comment]
- generalize Species to AbstractSpecies, with subtypes (coulomb, psp, ...)
- have a species (Vector of pairs (spec, pos)) field in Model
- make the functions that currently take `composition...` read from that field
- move the computation of number of electrons to Model (overwritable with a kwarg)

**Comment by antoine-levitt** [comment]
Why `Species` and not `Atom`, btw?

**Comment by antoine-levitt** [comment]
The reason I'm asking is because with `Atom` I can figure out what its plural is :D

**Comment by mfherbst** [comment]
Because in coarse-graining methods the entities of the unit cell might not be atoms, but more generic species :P

**Comment by mfherbst** [comment]
Plural is boring: **species** as well ... see [wiktionary](https://en.wiktionary.org/wiki/species)

**Comment by antoine-levitt** [comment]
Yeah but `species::Vector{Species}` is weird.

**Comment by mfherbst** [comment]
Agreed ... I don't have a better idea at the moment however. I'm also not in favour if "atoms" to be fair.
