### ISSUE TITLE
Investigate eigensolver bad convergence

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaMolSim/DFTK.jl#578]
When running the tests I sometimes see things like
┌ Warning: Eigensolver not converged
│   iterations =
│    9-element Vector{Int64}:
│     200
│       2
│       2
│     200
│       ⋮
│       2
│       2
│       2

which makes me thing something is going wrong in the eigensolver. Possibly this is something stupid like a much too small problem, but it might be a good opportunity to improve LOBPCG robustness / stopping criteria

**Comment by mfherbst** [comment]
It's the stopping criterion. In those tests we solve the SCF to death and thus the tolerance of the eigensolver is pretty low. Either it's below what is numerically achievable or we need to do some serious tolerance in the whole LOBPCG (e.g. ortho).

**Comment by antoine-levitt** [comment]
In that case there might be a way for LOBPCG to say it's not reasonable and declare convergence anyway

**Comment by mfherbst** [comment]
yes, that's what we should do. In fact I noticed that usually in those cases the residual starts to increase again because of numerical error, so stopping at the right spot would even give you the best result (in terms of the residual norm, but how that relates to the error in this regime is of course a different question.

**Comment by antoine-levitt** [comment]
That's a pretty tricky but very interesting question

**Comment by antoine-levitt** [comment]
Consider the simplest problem, solving Ax=b using xn+1 = xn - alpha (Axn-b), where alpha is fixed (let's say to its optimal value, 2/(lambda1+lambdaN)). Now when does it not make sense to run this iteration anymore? Basically when the increment is drowned out by noise, so when |alpha (Ax-b)| is of the same order of magnitude as the noise induced in computing it. The error in computing Ax-b in finite arithmetic is eps (|b| + |A| |x|). This turns out not to be super predictive for LOBPCG because it's much more complicated (in my very stupid tests it stops converging a full 1e3 before that bound). The question of the interaction between the acceleration and the stopping criteria is a super interesting one, but I'm afraid I don't have anything clever to say about that. Possibly the numerical linear algebra people have looked at this in the context of eg conjugate gradients?

**Comment by antoine-levitt** [comment]
A fun project would be to see if something clever can be said by eg employing linear error propagation (eg with julia's Measurements) at clever places (eg in the residual -> increment pipeline). In any case, the action for DFTK for now is to fix the tests to not require such a small tolerance. I'm pretty reluctant to introducing heuristics in LOBPCG based on stagnation monitoring or the like because that's very brittle.
