### ISSUE TITLE
Convergence monitoring

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaMolSim/DFTK.jl#579]
When eyeballing convergence, the usual thing is to look at a string of numbers like "1.24e-4" and trying to decypher from it whether it converges or not. It's pretty annoying to try to guess patterns from these numbers. Much more useful would be the log (and this is indeed how we plot them). In scripts I've taken to printing them as "1e" * log10(err), resulting in things like 1e-3.72. Then it becomes much easier to spot patterns. I feel it's also pretty readable for people who don't know about this convention, and am edging towards thinking this should be the universal thing to do for monitoring convergence. Maybe we should do that, eg for the default SCF convergence monitoring?

**Comment by mfherbst** [comment]
Sounds like a good idea to me, actually. Feel free to add that to the default callback.

**Comment by antoine-levitt** [comment]
```
n     Energy            Eₙ-Eₙ₋₁     ρout-ρin   α      Diag
---   ---------------   ---------   --------   ----   ----
  1   -7.926703358142               1e-00.70   0.80    4.4
  2   -7.931684890245   -1e-02.30   1e-01.52   0.80    1.0
  3   -7.931992462663   -1e-03.51   1e-02.43   0.80    3.2
  4   -7.931993443241   -1e-06.01   1e-03.24   0.80    2.7
  5   -7.931993461920   -1e-07.73   1e-04.48   0.80    2.1
  6   -7.931993463234   -1e-08.88   1e-05.34   0.80    3.3
  7   -7.931993463237   -1e-11.51   1e-06.40   0.80    2.2
  8   -7.931993463237   -1e-13.30   1e-07.14   0.80    2.4
  9   -7.931993463237    1e-14.75   1e-08.12   0.80    2.2
```
Do we like that? The 1e are a bit annoying. Alternative is printing log10(err) directly. That makes it harder to signal the sign of the dE though.
