### ISSUE TITLE
Employing DFTK results for Machine-Learning

### ISSUE THREAD

**Issue by exenGT** [JuliaMolSim/DFTK.jl#595]
Hi DFTK developers,

I would like to know how to pass the Julia Arrays generated by DFTK to python for postprocessing?

Thanks,
Jingyang

**Comment by antoine-levitt** [comment]
I tend to go the other way: do postprocessing in julia and call python when needed with pycall, which works very well. The other way is more annoying. Of course you can just write arrays to files (eg using HDF5, or any other format) and read them back from python. For a more direct interface maybe https://github.com/JuliaPy/pyjulia but I haven't tried it. @mfherbst also did https://github.com/mfherbst/asedftk but I don't know how advanced it is

**Comment by mfherbst** [comment]
Perhaps you could give us a better idea what kind of postprocessing you were thinking about? That could help us to give you a more matching answer.

Na asedftk is very much outdated. If it has what you need than it is probably the easiest, but indeed I would also recommend to do the postprocessing in Julia, if possible. Depending on what you want to do HDF5 is a good choice. Other ideas is [NPZ.jl](https://github.com/fhs/NPZ.jl) which is kind of light weight.

**Comment by exenGT** [comment]
Thanks for your reply! I'm thinking about doing some machine learning task in JAX. Nevertheless, I just found out about Flux.jl. Which package would you recommend?

**Comment by antoine-levitt** [comment]
I don't have any experience with either. @niklasschmitz might have an opinion.

**Comment by exenGT** [comment]
Thanks @mfherbst for the suggestion! I'll look into it. On the other hand, it would be nice to have the ase-dftk interface, as it could make use of the optimization / molecular dynamics engine available in ase.

**Comment by mfherbst** [comment]
>  it would be nice to have the ase-dftk interface

Oh I fully agree, it's just been a pain to maintain and no-one used it afaik. Also it is not broken. It just employs a rather old DFTK under the hood. I'm happy to give you pointers if you want to take a look in patching it up.

**Comment by exenGT** [comment]
Yes, I would be happy to. I'm getting familiar with Julia (and with DFTK) now, hopefully would be comfortable enough soon to work on the code! :)

**Comment by mfherbst** [comment]
> it could make use of the optimization / molecular dynamics engine available in ase.

One thing to add here: Optimisation can be easily done in Julia (Optim package, see the geometry optimisation example we have in the docs) and MD as well (Molly for example). There is some work over at https://github.com/cesmix-mit/Atomistic.jl/ to connect Molly and DFTK. So you can do all these things without ASE.
The main advantage of ASE in my opinion (and the reason for starting asedftk) is that there already is a lot of tooling building on top of ASE, but for those two tasks it will (soon) not be needed any more.

**Comment by exenGT** [comment]
> The main advantage of ASE in my opinion (and the reason for starting asedftk) is that there already is a lot of tooling building on top of ASE

I think as many people in the community are already familiar with ASE, asedftk could benefit from the many algorithms in ASE, and potentially other applications, e.g. using ASE in a high-throughput setting. Still, it would be worth to take a look at the Julia packages you mentioned!

**Comment by mfherbst** [comment]
I think the discussion has reached an end. Feel free to reopen @exenGT if you have more questions.
