### ISSUE TITLE
Proper type stability

### ISSUE THREAD

**Issue by mfherbst** [JuliaMolSim/DFTK.jl#60]
As discussed https://github.com/JuliaMolSim/DFTK.jl/pull/59 our code is still full of expressions, where a `Float64` result implicitly generated. This should be carefully investigated and made properly type-stable.

**Comment by antoine-levitt** [comment]
Problems are:
- Irrationals, eg T(pi) instead of pi
- Integer division, eg in kweights, bzmesh
- Integer special functions, eg sqrt in PspHgh, SphericalHarmonics

Grepping for `pi`, `/` and `sqrt` *should* be fine and catch them all.

**Comment by mfherbst** [comment]
Once #61 is merged, there are still two aspects missing:
- LDA implementation inside `xc_fallback/`
- `occupation.jl`

**Comment by antoine-levitt** [comment]
Once https://github.com/stevengj/ChangePrecision.jl/pull/11 (or similar) is merged we should be able to use that for LDA

**Comment by mfherbst** [comment]
I feel this has become solved or not relevant any more. Feel free anyone to reopen if they disagree.
