### ISSUE TITLE
Stronger type annotations for model construction

### ISSUE THREAD

**Issue by killah-t-cell** [JuliaMolSim/DFTK.jl#668]
I was playing around with some atom positions and came across this error

```
ERROR: LoadError: MethodError: no method matching spglib_atoms(::Vector{Vector{Int64}}, ::Vector{Array{Float64}}, ::Vector{StaticArrays.SVector{3, Float64}})
```

Whenever I defined positions like so `positions = [[0. 0. 0.],[1/2,1/2,1/2]]` instead of like so `positions = [ones(3) * 0.0,ones(3) * 0.5]`. Because the former is a `Vector{Array{Float64}}` and the latter is a `Vector{Vector{Float64}}`. I wouldn't expect this to matter as a new user, but maybe you have a reason for it, so I just wanted to flag.

Example code
```julia
temperature = 1e-3
Sc = ElementPsp(:Sc, psp=load_psp("hgh/lda/Sc-q3"))
Al = ElementPsp(:Al, psp=load_psp("hgh/lda/Al-q3"))
atoms = [Sc, Al]
lattice = 1.0 * I(3)

positions = [[0. 0. 0.],[1/2,1/2,1/2]] # this will fail
model = model_LDA(lattice, atoms, positions; temperature)

positions = [[0. 0. 0.],[1/2,1/2,1/2]] # this will work
positions = [ones(3) * 0.0,ones(3) * 0.5]

```

**Comment by antoine-levitt** [comment]
The issue is that `[0. 0. 0.]` defines a 1x3 matrix, instead of a Vector of size 3 (the julia syntax for defining matrices is inherited from matlab, which is not great). Maybe we should type the `atoms` and `positions` arguments in the `Model` constructor, what do you think @mfherbst?

**Comment by mfherbst** [comment]
Yes, I agree. I think I did that at least partially, but most likely not tight enough. These errors can indeed be annoying.

Thanks for testing @killah-t-cell !
