### ISSUE TITLE
Don't hardcode ylims in band structure

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaMolSim/DFTK.jl#674]

**Comment by mfherbst** [comment]
It's not hard-coded. You can always
```julia
p = plot_bandstructure(scfres)
ylims!(p, [-Inf, Inf])
```

**Comment by antoine-levitt** [comment]
Ah, right, thanks! (btw I still find plots atrocious, it's not easy to have two different plots, the GR backend can't zoom, inhibits ctrl-C and crashes after closing the window, and the PyPlot one complains my pyplot is too old)
