### ISSUE TITLE
Overly excessive `n_bands` by default for spin-polarised calculations

### ISSUE THREAD

**Issue by mfherbst** [JuliaMolSim/DFTK.jl#692]
In the function

https://github.com/JuliaMolSim/DFTK.jl/blob/7306c7dfdc9b19feaa14511e0d5524a387b9cf8b/src/scf/self_consistent_field.jl#L10-L12

I am not sure `filled_occupation` is the right thing to do here for spin-polarised as we now have spin-up and spin-down k-points.

**Comment by antoine-levitt** [comment]
Indeed. Should be n_bands_per_kpoint = div(n_electrons, 2) (at least until we implement non-collinear spin)
