### ISSUE TITLE
Test examples and expensive tests

### ISSUE THREAD

**Issue by mfherbst** [JuliaMolSim/DFTK.jl#70]
It would nice to explicitly test the examples and expensive tests from time to time. Perhaps using a different CI provider.

**Comment by antoine-levitt** [comment]
The examples are broken on master, so yeah I agree :-) I think the simplest is to make the examples less expensive (maybe by having a flag for fast tests at the beginning of the file?) so that they can be run on regular CI.

**Comment by mfherbst** [comment]
Yes, that's possible, but than they might quickly become difficult to read. 

As we discussed before, from my understanding examples should be easy and commented and top to bottom. That's why I already have trouble with the silicon example you made (but there it's still ok). If we on top add some `if`s for CI special cases it definitely gets a lot worse.

I start to think more and more that a good way around it is to not have example files as we have them now, but instead some sort of "template" files in the repo, in which one replaces parts of the file to produce plain example files and/or actual test cases to be run in the unit tests. That way the things do not get out of sync so easily and at the same time the examples become again simpler (top to bottom, no ifs). Might be a bit over the top, however ... what do you think?

**Comment by antoine-levitt** [comment]
The nice thing about examples as they are now is that they're easy entry point for people to figure out how stuff works and how to coerce DFTK to do what you want it to (ie how to access densities, orbitals, etc...). That often means having multiple options in the same file that people can play with. That kind of examples is much more effective than a thorough code documentation (which tends to grow huge, unorganized and outdated), in my opinion. Maybe we can just have "simple" examples, and some more involved, with ifs.

I agree the current silicon is not great (the main goal there was reducing code duplication while the interface was still being worked on), but we should be able to mitigate that but eg moving the supercell functionality, and getting rid of "standard_models.jl" in favor of explicit hamiltonian construction. I'm not a favor of a template system, but we could maybe have some common files, like in silicon_runners.
