### ISSUE TITLE
Failling CI

### ISSUE THREAD

**Issue by epolack** [JuliaMolSim/DFTK.jl#730]
Tests are currently failing for PR for some `Illegal instruction`.

**Comment by antoine-levitt** [comment]
@gkemlin has the same issue in https://github.com/JuliaMolSim/DFTK.jl/pull/728

**Comment by gkemlin** [comment]
Yes, it is a bug in Brillouin.jl. I try to setup an example to open an issue.

**Comment by mfherbst** [comment]
Let's discuss in  thchr/Brillouin.jl#21
