### ISSUE TITLE
Rename q=k+G to something else

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaMolSim/DFTK.jl#753]
We currently use q for general Fourier vectors, eg q=k+G, but we really want to use q for supercell wavevectors, like k, typically to do phonons. It'd be nicer to have separate symbols. How about using p for k+G?

**Comment by azadoks** [comment]
Somewhere in the literature / pseudo documentation, I've seen K for k+G, which seems reasonable.

**Comment by antoine-levitt** [comment]
Hm, I kind of like caps for lattice vectors, it's a nice convention. I actually liked K for G, which gives a nice symmetry (k/K, r/R) but the G convention is kind of universal...

**Comment by mfherbst** [comment]
To be fair, I don't mind whatever as long as it's consistent. So i'd go for lower-case. `p` seems reasonable. I don't think we have given it some meaning anywhere else.

**Comment by mfherbst** [comment]
ok, fine for me

**Comment by antoine-levitt** [comment]
OK, let's get the psp PR in, and I'll do the rename before @epolack 's phonons PR

**Comment by antoine-levitt** [comment]
👍
