### ISSUE TITLE
Remove remaining ASE-dependent code

### ISSUE THREAD

**Issue by epolack** [JuliaMolSim/DFTK.jl#756]
Mainly as a todo.

- [ ] @epolack adds supercell creation in `AtomsBase`
- [x] Light-weight ASE to AtomsBase package (`ASEimport` ?) (see [ASEconvert.jl](https://github.com/mfherbst/ASEconvert.jl))
- [x] Remove ASE-dependent code from DFTK base
- [ ] Keep an example how to integrate with ASE structures (and update `https://dftk.org/q/ase` to point there)

**Comment by mfherbst** [comment]
Closing this as supercell creation is pretty convenient using ASEconvert.
