### ISSUE TITLE
Unsure about role of `l_local` in UPF

### ISSUE THREAD

**Issue by azadoks** [JuliaMolSim/DFTK.jl#765]
In UPF pseudos, there is a header tag `l_local` which is commonly set to -1 (in our implementation, I think we *assume* it's set to -1). 

I'm not sure that it's ever set to something other than -1 in practice, but if it is, I think local potential replaces the projectors at the given angular momentum (this is explained in the PSP8 documentation, which similarly has `lloc`).

In this case, I'm not sure if we are computing the correct integral in `eval_psp_local_fourier`. Currently, we assume `l=0` where `j_l(x) = sin(x) / x`. I'd guess that if `l_local` is set to an angular momentum channel, we should use the spherical bessel of that channel.

This could easily be fixed (if it needs to be) by storing `l_local` in `PspUpf` and replacing the hard-coded `sin(x) / x` with a call to `sphericalbesselj(l, x)`.

**Comment by antoine-levitt** [comment]
I don't think your interpretation is quite right : for instance it would mean no long range Coulomb term. I recall something similar in the construction of pseudos : you construct a local potential for each AM channel, then you decide arbitrarily to pick one of those for the global local potential and convert the other AMs to KB format. I don't think it makes any sense for psps specified directly in KB format, which is probably why it's set to -1. I'd just assert it's -1 and worry about it later.
