### ISSUE TITLE
Replace Density

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaMolSim/DFTK.jl#78]
Things I like about the current Density

- Frees us from having to think about whether we have computed the Fourier or not, which is extremely nice
- We can do it lazily

Things I don't like

- It's not specific to density, we can do potentials in the same way.
- It's not clear whether it should be a real thing or not
- It doesn't support a lot of functionality, it's mainly a container type
- We spend a lot of time converting back and forth; eg `rho_real = real(rho)` which is pretty confusing. Possibly fixed by the previous thing
- `real` is bad; eg `imag(real(rho))` is very weird

Suggestions for names:
- GridArray (it's an array, it's on a grid)
- CrhoArray. Consistent with our notations (once we figure out what they are), but idiosyncrasic => bad
- FourierArray (it's an array with its own Fourier inside)

I'm leaning towards FourierArray. 

To replace `real` I suggest we use the `getproperty` overload in julia to transparently intercept calls to `arr.real` (and compute it lazily if we need to).

We can parametrize by a type that tells us whether the array in real space is real (in which case the fourier representation might be a compressed one, at least in the future).

We could also think about moving `basis_Crho` (which we should maybe rename) closer to that array in the code.

We can easily support broadcast in a trivial way, which would simplify some things, eg
`density_from_real(basis, real(ρin) .+ m.α .* (real(ρout) .- real(ρin)))` becomes way nicer. Con: I don't know how easy it is to support broadcast on custom types. See julia issue 33453

**Comment by antoine-levitt** [comment]
For `basis_Crho`: `G_vectors`? Together with `r_vectors`. Also define `G_vectors(A::FourierArray) = G_vectors(A.basis)`? That would make for a nice and consistent API

**Comment by antoine-levitt** [comment]
Has the added benefit that we can implement real arrays with compressed storage in G by overloading `G_vectors` to just return half of them. Possibly too fancy and bug-prone though...

**Comment by antoine-levitt** [comment]
Oooh and we can be extra fancy and define constructors that take functions and evaluate them on the grid.

**Comment by mfherbst** [comment]
I mostly agree, apart from names ;).

I like the idea of overwriting `getproperty` and storing the notion of "real in real-space". One could later have some sort of a view structure for things like `G_vectors` to have the folding error-free. I kind of recall someone in FFTW was working on that. 

`FourierArray` feels a bit like the array only has the Fourier coefficients. Also it's not a real array as in the sense of an `AbstractArray`, because it has a notion of a basis and it represents a discretised quantity. I'm thinking about a name ...

**Comment by mfherbst** [comment]
So ... just to have it in written: `RealFourierArray` :smile:

**Comment by mfherbst** [comment]
Oh and we should have a `G_vectors(kpt)` and `G_vectors(basis, kpt)`.
