### ISSUE TITLE
crash with PyPlot

### ISSUE THREAD

**Issue by epolack** [JuliaMolSim/DFTK.jl#807]
I tested with Julia 1.8.4 and latest:
```julia
using PyPlot
using DFTK
```
segfaults with the latest version of PyPlot and DFTK.
With DFTK 0.5.14, it seems alright.

**Comment by antoine-levitt** [comment]
This is likely because of the use of PythonCall. Can you try PythonPlot instead of PyPlot? @mfherbst didn't you say this wouldn't happen? Can we maybe print a warning or something like that?

**Comment by antoine-levitt** [comment]
@mfherbst can we revert while we sort this out? It's pretty breaking and very confusing for people not aware of this.

**Comment by mfherbst** [comment]
So if you think that's too much of an issue we can just release the current master as 0.6.1 and then people who don't use ASEconvert should be good either way.

**Comment by mfherbst** [comment]
not really because the segfault happens before the `using` terminates.

**Comment by antoine-levitt** [comment]
This seems to work:
```
julia> @isdefined PyPlot
false

julia> using PyPlot

julia> @isdefined PyPlot
true
```
so we can print a warning if PyPlot is defined?

**Comment by mfherbst** [comment]
Yeah, but why does it make sense to warn about PyPlot incompatibility with ASEconvert in DFTK? This essentially happens any time you want to use any PyCall-based package and any PythonCall-based package. DFTK hard-depends on neither. Why should DFTK warn about this?

**Comment by antoine-levitt** [comment]
Seems worthwhile to try to do something about it, even if we're downstream from the issues. That, or we ask the PyCall/PythonCall to warn/error if they detect the presence of the other? Point is I don't want to turn people off from DFTK because of weird errors.

**Comment by mfherbst** [comment]
Closing as https://github.com/JuliaRegistries/General/pull/75061 merged.
