### ISSUE TITLE
Bors

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaMolSim/DFTK.jl#81]
It's a bit annoying to have to wait for CI to be green before merging. I've seen people use https://github.com/bors-ng/bors-ng, where you just leave a comment that it looks good to merge, and it'll merge it automatically when CI is OK (if I understand correctly). That could be nice, and it looks easy enough to setup. @mfherbst I'll do it if you agree.

**Comment by mfherbst** [comment]
Na I'm not a too big a fan of Bors. I think it's pretty intrusive and needs a lot of permissions (e.g. commit rights to master). Right now the amount of effort is manageable I think.

**Comment by antoine-levitt** [comment]
You think it's going to install malware on master? It's OK, but it means that

- we have to wait until CI is green to merge PRs that are good to go if CI is OK
- when we merge multiple orthogonal PRs at the same time, we have to manually update them and wait for CI each time

**Comment by mfherbst** [comment]
Sure, for that stuff Bors is made ;).

**Comment by mfherbst** [comment]
Don't you think that effort is manageable so far?

**Comment by antoine-levitt** [comment]
Sure I do, the main problem is that now one of us has to eg remember to merge https://github.com/JuliaMolSim/DFTK.jl/pull/80 when CI is done, and I'm much more comfortable with a "push" than "poll" workflow (because I don't like to have to remember things). But I can live with it. I'm generally pretty trusting when it comes to these things (because the ratio of benefit to effort of somebody trying to screw us is very very low), but I respect a good paranoia :-p

**Comment by mfherbst** [comment]
I agree. I just think what happened to pypi the other day. Let's get to Bors when we need to.

**Comment by mfherbst** [comment]
I'm starting to get tired of keeping track of PRs. Any disagreement if we move towards https://github.com/bors-ng/bors-ng now?

**Comment by antoine-levitt** [comment]
Of course! I was in favor before :-)

**Comment by mfherbst** [comment]
Cool. I'll do it then.
