### ISSUE TITLE
Usage Support: Adding DFTK.jl to Matsci Discourse Community

### ISSUE THREAD

**Issue by stefanbringuier** [JuliaMolSim/DFTK.jl#833]
@mfherbst I was wondering if the DFTK.jl team would be interested in requesting/starting a category on [Matsci discourse](https://matsci.org/) for DFTK.jl? The goal would be to focus more on user support discussions.

Guidelines are given [here,](https://matsci.org/faq#charter) and the request form for a new project/category is [here](https://docs.google.com/forms/d/e/1FAIpQLSceXN6Cf5y-YWKWtKPCECyVlpqsY9OpucK79mUvNzLgjg7nLw/viewform).

It could be that the category to be created is one-level up, meaning it is for JuliaMolSim org., if that makes more sense.

**Comment by mfherbst** [comment]
Dear Stefan thanks for contacting us about this matter. While I very much like the idea to have to have such a general discourse board for discussion, but I think for us participating is still a bit too early. Our user base is still small and I think it's better to avoid fragmentation across too many portals when it comes to providing user support. So far we've been using github or the [JuliaMolSim zulip](https://juliamolsim.zulipchat.com) chat, where traffic overall has been moderate.

I'll contact the JuliaMolSim people in general and see if there is some interest to get a category for all of us. In any case if you see more traffic with DFTK-related questions or user requests to open a DFTK category, I'd certainly happy to get involved.

**Comment by stefanbringuier** [comment]
Totally understand wanting to avoid fragmentation, I also forgot about the [zulip](https://juliamolsim.zulipchat.com/login/) chat. The reason I brought this up is I get questions from people I recently pointed to DFTK.jl and for inquiries where I don't know the answer I thought of pointing them to Matsci discourse, but I'll send them over to the [zulip](https://juliamolsim.zulipchat.com/login/) chat.

**Comment by mfherbst** [comment]
Great. Thanks.

I'll close this for now, but feel free to reopen if there are updates.
