### ISSUE TITLE
Mixed Reduced and Cartesian coords in apply_symop ?

### ISSUE THREAD

**Issue by LaurentVidal95** [JuliaMolSim/DFTK.jl#837]
Hello everyone,

While trying to use the SymOp and `apply_symop` operations in DFTK for a project with @epolack, we found out a strange thing that we don't understand.

In `SymOp.jl`, SymOp are defined by giving a Cartesian real space coordinate matrix W and shift w. Then the S and and `\tau` applying to reciprocal space are simply defined by `S = W'` and `\tau=-W / w` so that they also apply to reciprocal vectors in cartersian coordinates.

The problem is that in `apply_symop`, the matrix S is directly applied to `kpt.coordinate` which is in reduced coordinates. So it seems that we're mixing cartesian and reduced.

Is that so ? Or is there anything we don't understand ?

Best

**Comment by antoine-levitt** [comment]
Fixed by https://github.com/JuliaMolSim/DFTK.jl/pull/840, thanks!
