### ISSUE TITLE
Rounding issues cause bad wannier interface

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaMolSim/DFTK.jl#844]
Wannierisation failed because of this very nice footgun: 
```julia
julia> unique([0.0, -0.0])
2-element Vector{Float64}:
  0.0
 -0.0
```

Amusingly this fixed it:
```julia
@@ -337,7 +337,7 @@ function unfold_kcoords(kcoords, symmetries)
     # the above multiplications introduce an error
     unique(all_kcoords) do k
         digits = ceil(Int, -log10(SYMMETRY_TOLERANCE))
-        normalize_kpoint_coordinate(round.(k; digits))
+        normalize_kpoint_coordinate(round.(k; digits) .+ 0.0)
     end
 end
```
I haven't found any way of making `unique` use `==` instead of `===`, so the above might be our best bet, unless somebody has a better idea... cc @LaurentVidal95 @ELallinec

**Comment by mfherbst** [comment]
How reliable is this? Maybe shift by Tol before round & unique, then shift back?

**Comment by antoine-levitt** [comment]
I think zero is the only place where there's an issue, because it's the only place where round(x) === round(y) is false even when both x and y are close to the same round number

**Comment by mfherbst** [comment]
Ok makes sense. Then I'd assume IEEE enforces some sort of normalisation of the signs? At least a plain `-0.0 + 0.0` yields the same result.

**Comment by antoine-levitt** [comment]
-0.0+0.0 is 0.0 as a result of the IEEE rounding rules
