### ISSUE TITLE
unit and equation of calculated force 

### ISSUE THREAD

**Issue by s-zorrieh** [JuliaMolSim/DFTK.jl#847]
Hi. I wanna know from which equation the `calculate_forces(scfres)` was written? and what is its demention?

**Comment by antoine-levitt** [comment]
Hi, I'm not sure I understand your question. This computes the forces (derivatives of energy with respect to atomic positions). You can find more information for instance in the book "electronic structure" by Martin. compute_forces is in reduced units, compute_forces_cart is in cartesian units (hartree over bohr)

**Comment by mfherbst** [comment]
Closing this for now, as the question seems answered. Feel free to reopen @s-zorrieh if you still would like to know more.
