### ISSUE TITLE
how to customize/define an xc functional

### ISSUE THREAD

**Issue by MuhammadAlijad** [JuliaMolSim/DFTK.jl#848]
Hello, 

Is there a simple way to customize the xc functional or the xc potential used in the Kohn-Sham Hamiltonian? for example: similar to PySCF code: https://github.com/pyscf/pyscf/blob/master/examples/dft/24-define_xc_functional.py   

Thanks

**Comment by antoine-levitt** [comment]
For LDA type xc functionals you can also use LocalNonlinearity, see the gross pitaevskii example
