### ISSUE TITLE
Minus sign in Fourier transform of projectors

### ISSUE THREAD

**Issue by qiaojunfeng** [JuliaMolSim/DFTK.jl#855]
While I was rewriting the Wannier interface (#854), I need to project Bloch states onto localized orbitals, so I need sth similar to `build_form_factors` here,
https://github.com/JuliaMolSim/DFTK.jl/blob/ff7f6624f050651961f3b299254baf76a04a48be/src/terms/nonlocal.jl#L219-L225

However, when I check the equations, I think it should be `(-im)^l` instead of the current `im^l`. I wrote down some formulas here
https://wannierjl.org/theory/initial_projection/
and some numerical tests here
https://wannierjl.org/theory/pluto_fourier

I uses `(-im)^l` in the #854, in principle this is just a phase factor of wavefunctions. But for instance, if we were to construct a linear combination of `s` and `px` orbitals, then this minus sign will give us different results, `s+px` or `s-px`, so maybe we should also update the `build_form_factors`？

**Comment by qiaojunfeng** [comment]
@azadoks maybe you also paste here the table containing investigations on the QE subroutines? Thanks a lot!

**Comment by azadoks** [comment]
```
Wannier90 interface in QE:  (-i)^l
Atomic WFC code in QE:      (+i)^l
Non-local projectors in QE: (-i)^l
Wikipedia:                  (-i)^l
DFTK code:                  (+i)^l
DFTK docs:                  (-i)^l  (equivalently written as ylm_real(-r/|r|))
ABINIT:                     ??????
```

**Comment by antoine-levitt** [comment]
I went ahead and did it: https://github.com/JuliaMolSim/DFTK.jl/pull/856

**Comment by qiaojunfeng** [comment]
> I went ahead and did it: #856

Thanks a lot for the clarification, this is great!

**Comment by mfherbst** [comment]
Thanks for flagging this @qiaojunfeng !
