### ISSUE TITLE
Terms interface

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaMolSim/DFTK.jl#86]
The current design has served us well but:
- it's specialized to "basic" DFT, doesn't really support eg Fock terms (where the hamiltonian depends on the psi and the occupations, not just the density) and magnetic fields (where the hamiltonian application needs gradients of psi)
- it hardcodes a list of predefined terms (kinetic, external, hartree, xc, nonlocal). It'd be nice to have an interface that lets the terms pick and choose what information they need
- energies sort of come as an afterthought. Eg the psp and ewald energies should be terms like the others (they just happen not to depend on the psi)
- After thinking about it a lot, I think this interface where the terms are called separately for the energy and potential, and have to ask for if things are nothing or not and fill them is annoying. A term, when called, should output its energy, and a lazy object that is able to compute gradients if they are needed. That frees the caller from having to figure out exactly what temporaries the term needs.

I think we should come up with a design for the most general situation possible, where we want to do direct minimization wrt the psi_nk and their occupation for eg Hartree-Fock. Then we try to join with the current design.

Mathematically, a term is a function E(D) of the density matrix (in our case represented as Psi and their occupations for all kpoints). From that we want to compute E(D) and H = nabla E(D). H is block diagonal in the sense that it maps Bloch waves to Bloch waves, which leads to Hk. Hk is something that takes as input a psi (represented by a list of coordinates in the G basis), and outputs Hk psi.

Performance-wise, I think we can do pretty much what we want (closures left and right, allocations of whatever), provided we don't screw up on the application of Hk to vectors.

So, just to get the ball rolling, how about Model contains a list (ie tuple) of terms. Each term is something that can be called like `term(basis, Psi, occupation)` and returns an energy, as well as an HamiltonianTerm object, that can store whatever it wants inside, and can be called like `ham_term(kpoint, Psi)`. `HamiltonianBlock` would then contain a list of these things and wrap `mul!` around that.

Ignoring optimizations, I think this is a nice design. Now of course the big problem with this is that terms need psi in some space and output it in some other space (eg the magnetic term needs psi in reciprocal space and outputs it in real space; not sure about the fock term, should check that). We handle this currently in `mul!` in HamiltonianBlock by knowing what the terms are and how they like to be called. It'd be great if we could invert the control somehow. Traits could be one answer (ie terms could implement `IsRealSpace(Term)`). Another answer could be RealFourierArray. But maybe the simplest is simply to have them work as `ham_term(kpoint, Psi_real, Psi_fourier)` and output `(HPsi_real, HPsi_fourier)` (which are then accumulated then Fourier transformed)?

We miss the current optimization that we accumulate all local potentials into one, but that logic we can potentially implement by term fusion (eg if multiple terms declare -eg through traits- that they're local potentials, we can fuse them).

(I promise, this is my last "hey, let's redesign DFTK completely" :-p If we manage to do something like the above, we should be good for a while - at least, until we get to response properties...)

**Comment by mfherbst** [comment]
Generally I like your thoughts. If you think at my [molsturm](https://molsturm.org) project, it actually is very similar in the sense that using laziness you can make all terms (whether constant wrt Psi or anything else) behave the same on an abstract level.

Questions I have:
- I suppose `term` is already a higher-level object (like we have now for XC), which may be any callable.
- Why `ham_term(kpoint, Psi)`? I actually think it makes more sense to have `Block` objects like we have for `Kinetic` and `Hamiltonian` as a complete thing, don't you think? These can than have a normal `mul` operator and the interface to be represented as a matrix. That can be really nice to have if you want to play and debug and if you wrap that in some nice code, it's not actually extra effort, I think.

Extra ideas
- I propose the term interface to be `term(basis, state)` where `state` is a datastructure containing the Psi and the occupation and *caches* all other quantities, i.e. the density as a `RealFourierArray`, the derivatives of the density, the gradients of psi and basically anything else, which the terms could need. Then the first time an accessor function like `density(state)` is called that respective object is computed and stored. That absolves you from·
- A lot of the things like term fusion can be done by multiple dispatch and abstract types. I know you are not a fan of big type hierachies, but I start to think it makes sense here, as starting to play with the returned tuple and extra trait functions really boils down to the same thing, but is less tractable than a nice type name in my opinion.

**Comment by antoine-levitt** [comment]
Bits of code from the discussion:
```
function apply_ham(Psi)
    Hks = replace_stuff(Hks)
    for iband = 1:nband
        out_real = zeros
        out_four = zeros
        in_four = Psi[:, iband]
        in_real = ifft(in_four)
        for Hk in Hks
            mul!((four=out_four, real=out_real), Hk, (four=in_four, real=in_real), 1.0, 1.0)
        end
    end
end

abstract type Hamk end
abstract type MultiplicationOperator <: Hamk end
pot(MultiplicationOperator) = ...



abstract type AbstractTerm end

function e+h(T::AbstractTerm, basis, Ψ, occ)
end

e+h(Kinetic(basis), basis, Ψ, occ)

(T::AbstractTerm)(basis) = T()

struct Kinetic <: AbstractTerm
end
```

**Comment by antoine-levitt** [comment]
OK, what do you think of the following design?
```julia
# call as energy(t::AbstractTerm, Psi, occ, ρ) -> energy, Hks
abstract type AbstractTerm end



struct Model
    ...
    term_types::Vector # Must implement t(basis) -> AbstractTerm
end
struct PlaneWaveBasis
    ...
    terms::Vector{AbstractTerm}
end
function PlaneWaveBasis(M::Model, ...)
    basis = ...
    PlaneWaveBasis(basis.a, basis.b, ..., [t(basis) for t in M.term_types])
end




function get_new_Psi(basis::PlaneWaveModel, Psi, occ, ρ)
    ρ = ρ(Psi, occ)
    EH = [energy(t, Psi, occ, ρ) for t in basis.terms]
    ene = sum(eh[1] for eh in EH)
    ham_terms = [[EH[it][ik] for it = 1:length(EH[1]) ] for ik = 1:length(basis.kpts)]
    # Each kpt calls apply_ham(basis, kpt, Psi, ham_terms[ik])
end

function apply_ham(basis::PlaneWaveModel, kpt, Psi, Hks)
    for t in basis.terms
        # Hks = replace_stuff(Hks)
        for iband = 1:nband
            out_real = zeros...
            out_four = zeros...
            in_four = Psi[ik][:, iband]
            in_real = ifft(in_four)
            for Hk in Hks
                mul!((four=out_four, real=out_real), Hk, (four=in_four, real=in_real), 1.0, 1.0)
            end
        end
    end
end





struct FourierSpaceMultiplication
    multiplicator
end
function mul!(C, T::FourierSpaceMultiplication, A, α, β) = C.fourier .+= α .* C.fourier .+ β .* T.multiplicator .* A.fourier
struct RealSpaceMultiplication
    potential
end
function mul!(C, T::RealSpaceMultiplication, A, α, β) = C.real .+= α .* C.real .+ β .* T.potential .* A.real



struct Kinetic <: AbstractTerm end
Kinetic(basis) = Kinetic() # no setup needed; or maybe precompute kinetic energies...
function energy(K::Kinetic, basis, Psi, occ, ρ; kwargs...)
    e = ...
    kin = [... for k in basis.kpoints]
    e, [FourierSpaceMultiplication(kin[ik]) for ik = 1:length(basis.kpoints)]
end


External(V::Function) = basis -> ExternalTerm(basis, V.(r_vectors(basis)))
struct ExternalTerm
    basis
    pot
end
function energy(T::ExternalTerm, basis, Psi, occ, ρ; kwargs...)
    e = sum(T.pot .* ρ), [RealSpaceMultiplication(T.pot) for ik = 1:length(basis.kpoints)]
end

struct Hartree <: AbstractTerm end
Hartree(basis) = Hartree() # no setup needed, or maybe precompute G^2 or something...

function energy(T::Hartree, basis, Psi, occ, ρ; kwargs...)
    pot = ρ ./ Gsq
    sum(pot .* ρ), [RealSpaceMultiplication(T.pot) for ik = 1:length(basis.kpoints)]
end

```

**Comment by mfherbst** [comment]
Generally I like it.

Some comments:
- I still think the vector of terms should be a different object, because than something like `Matrix(object)` works to get the complete Hamiltonian as an object.
- I think for the sake of having a consistent interface, all `AbstractTerm` objects should have the basis inside. You pass it anyways on construction, so why not keep it?
- It could hit us later, that we have circular references (PlaneWaveBasis contains terms, which contains the PlaneWaveBasis). Does not matter for now, really, but my experience is that if this can be avoided one should to reduce complexity.
- `get_new_Psi` ... should be the SCF map inside the SCF solver, right?

Bikesheding:
- `PotExternal` instead of `External` and `PotHartree` instead of `Hartree` ...
- `eneham` instead of `energy` or `energy123` for later replacement ;)

**Comment by antoine-levitt** [comment]
So I'm on this and I came up with things like this:
```julia
struct PowerNonlinearity
    basis::PlaneWaveBasis
    α::Real
end
PowerNonlinearity(α::Real) = basis -> PowerNonlinearity(basis, α)

struct Kinetic
    basis::PlaneWaveBasis
    kinetic_energies::Vector{Vector} # kinetic energy 1/2|G+k|^2 for every kpoint
end
function Kinetic(basis::PlaneWaveBasis)
    kinetic_energies = [[abs2(basis.model.lattice * (G+kpt.coordinate))/2
                         for G in G_vectors(kpt)]
                        for kpt in basis.kpoints]
    Kinetic(basis, kinetic_energies)
end
Kinetic() = basis -> Kinetic(basis)
```
so that we don't have to have separate names for the "builder" and the term itself: the user can just do Model(..., [Kinetic(), PowerNonlinearity(2), ...]) without caring that the term object that's going to be used in the rest of the code is going to be a slightly different object. Do you think that's too confusing? A downside is that there's no real way to know what a term is in a Model until it's instantiated with a basis. The alternative would be to have things like [KineticBuilder(), PowerNonlinearityBuilder(2)] which I don't like very much...

**Comment by mfherbst** [comment]
Nice idea, but I think that's too fancy. I am certain we will end up confusing `Kinetic` returning a function and `Kinetic` returning an object depending on how it's called.

I agree that the alternative of appending `Builder` is not appealing, but then why not do the reverse? `Kinetic` is the builder and `TermKinetic` is the concrete thing containing the `kinetic_energies` and so on. That's roughly what we have now and it does not break with your design either, plus the more clumsy thing is hidden.

**Comment by antoine-levitt** [comment]
OK, I've pushed the new design to branch termpocalypse, without integration in the code itself. There's a *lot* of code churn there, it's a little bit scary... I'm not sure when I'll have the time to do it, we'll see.

**Comment by antoine-levitt** [comment]
It's needed for a release though, which I'd like to do sooner rather than later. I'm still tinkering with the design, let's check in next week and see.

**Comment by antoine-levitt** [comment]
Could you take a look at the new files in `terms/` in that branch? In particular `terms.jl`. A bit of complexity (like the RealFourierOperator thing) stems from the fact that we need to avoid computing too many FFTs, and feels a bit clunky (and pretty specific to plane wave). Maybe we should have another RFA-like abstraction instead? That design seems good enough for now though, and decouples things sufficiently that they can be modified more easily later on if needed.
