### ISSUE TITLE
Explained examples and tutorial-style documentation

### ISSUE THREAD

**Issue by mfherbst** [JuliaMolSim/DFTK.jl#87]
One option to better embed examples into the documentation without code duplication could be [Weave.jl](https://github.com/JunoLab/Weave.jl). For their own documentation they use Documenter, so it could at least be compatible.

**Comment by mfherbst** [comment]
The idea would be to also explain third-party tools to setup the computation. For example ASE or pymatgen and helpful aspects of their usage (visualisation etc).

**Comment by antoine-levitt** [comment]
Let's just use a notebook for this, in the style of Silicon_Graphite.ipynb.

**Comment by mfherbst** [comment]
I'm not completely convinced about that. We have to be a little careful to not scatter the documentation over too many things. Notebooks definitely seems for such aspects, however.

**Comment by antoine-levitt** [comment]
For demonstration purposes notebooks are really nice. We should have a tutorial/ dir at the toplevel with just notebooks. It doesn't replace the examples, which are more complete, more low-level and more concise. It does mean that we split things between 1) the code 2) the examples 3) the tutorials 4) the docs 5) the tests. If we remove 4) (ie keep it like what we have now) I think it's not too bad.

**Comment by mfherbst** [comment]
I think it is starting to. Every time you change something in the interface you have to keep it up to date. I'm just raising to think about it and about clever options (like autogenerating parts of one thing from the other) before really going into splitting stuff up too much.

**Comment by mfherbst** [comment]
What could be helpful for this is [Literate.jl](https://github.com/fredrikekre/Literate.jl).
