### ISSUE TITLE
ExtXYZ segfault

### ISSUE THREAD

**Issue by epolack** [JuliaMolSim/DFTK.jl#889]
pin to remember to revert part of the commit from https://github.com/JuliaMolSim/DFTK.jl/pull/882, which bypassed a segfault in the use of the AtomsIO package.

**Comment by mfherbst** [comment]
It's not AtomsIO, which is the culprit, it's ExtXYZ and a fix should be in general according to https://github.com/libAtoms/extxyz/issues/15.
