### ISSUE TITLE
Test that hamiltonians and energies are consistent

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaMolSim/DFTK.jl#92]

**Comment by antoine-levitt** [comment]
Note that we need to test for that for both spinless and spinful. I'm very confused by the comment on factors of 2 in term_hartree.jl; need to check that more seriously.

**Comment by antoine-levitt** [comment]
Fixed by https://github.com/JuliaMolSim/DFTK.jl/pull/130. @mfherbst let's discuss the rationale for the normalization for the XC/Hartree terms sometime

**Comment by mfherbst** [comment]
Very happy to do that. Since it is related to spin, it will probably resolve naturally anyway when we have that part done.

**Comment by antoine-levitt** [comment]
But actually I think it's just that the comment is wrong. The total density is rho, the hartree energy has a factor of 1/2 (because of double counting), the xc energy doesn't (by definition). That has nothing to do with spin?

**Comment by antoine-levitt** [comment]
To be more clear: the energy is as above. The hamiltonian is defined by the relationship dE/dpsi_n = 2 fn H psi_n, and so for hartree and xc terms dE/dpsi_n = dE/drho drho/dpsi_n = 2 fn dE/drho psi_n. No spin at all.

**Comment by mfherbst** [comment]
That sounds reasonable.

What I had in mind is that ρ is the total density for us, but in the trace of a α-β-block-diagonal Hartree operator the α block would only be traced with the α density only and the β block only with the β density, so ρ/2 (in the non-collinear case), but then there is both the α and the β part of the trace, which is equivalent, so a factor of 2 again.

If you do it with collinear spin, however, then Jα is traced with ρα and Jβ is traced with ρβ separately and the results are added. So while Jα = Jβ and they are built from the total density ρ, the ρα and ρβ are not equivalent obviously.

For XC it's the same just that in the collinear spin case Kα != Kβ.

**Comment by antoine-levitt** [comment]
I think the hamiltonian picture is misleading here. The fundamental quantity is the energy, and that involves the total density.

**Comment by mfherbst** [comment]
Yes, but it also involves the spin density ... or in other words the α and β density. It's just a question of parametrisation, I'd say.
