### ISSUE TITLE
Include `Manifest.toml` in the repo?

### ISSUE THREAD

**Issue by Technici4n** [JuliaMolSim/DFTK.jl#922]
Shouldn't it be included in the repo? It seems that it would make keeping track of dependency updates from upstream easier, and it would ensure a reproducible build environment.

**Comment by antoine-levitt** [comment]
To add more details: if everybody follows semver (which people mostly do), you don't need to pin versions to avoid breakage. To get reproducibility, eg for papers, you just put together your experiment scripts with a manifest. There are some examples in https://docs.dftk.org/dev/publications/
